### ISSUE TITLE
Blocking call detected in MonoRateLimiter

### ISSUE THREAD

**Issue by amrynsky** [resilience4j/resilience4j#1049]
Resilience4j version: 1.5.0
Java version: 13

Test project: [reactive-client.zip](https://github.com/resilience4j/resilience4j/files/4839386/reactive-client.zip)

While evaluating resilience4j rate limiter for our reactive WebClient we observed a blocking call coming from `RateLimiter.reservePermission`

```
reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
	at jdk.internal.misc.Unsafe.park(Unsafe.java) ~[?:?]
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:359) ~[?:?]
	at io.github.resilience4j.ratelimiter.internal.AtomicRateLimiter.compareAndSet(AtomicRateLimiter.java:185) ~[resilience4j-ratelimiter-1.5.0.jar:1.5.0]
	at io.github.resilience4j.ratelimiter.internal.AtomicRateLimiter.updateStateWithBackOff(AtomicRateLimiter.java:163) ~[resilience4j-ratelimiter-1.5.0.jar:1.5.0]
	at io.github.resilience4j.ratelimiter.internal.AtomicRateLimiter.reservePermission(AtomicRateLimiter.java:127) ~[resilience4j-ratelimiter-1.5.0.jar:1.5.0]
	at io.github.resilience4j.ratelimiter.RateLimiter.reservePermission(RateLimiter.java:651) ~[resilience4j-ratelimiter-1.5.0.jar:1.5.0]
	at io.github.resilience4j.reactor.ratelimiter.operator.MonoRateLimiter.subscribe(MonoRateLimiter.java:39) ~[resilience4j-reactor-1.5.0.jar:1.5.0]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(FluxRetryWhen.java:204) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onNext(FluxRetryWhen.java:250) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:274) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:851) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:147) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
```

Here are our use cases.  There are 2 basic patterns we are testing. In both cases we assume that application logic is trying to execute much more than it's allowed by rate limiter. 

- sequential task - continuously fetch data from the same external source using multiple independent polling tasks that share the same `RateLimiter`.
```
        private Flux<String> sequentialTask(TestWebClient client, int ctx) {
		return client.request(ctx)
				.expand(res -> client.request(ctx));
	}
```

- parallel task - continuously fetch data from multiple external sources in parallel using. For example, there are multiple users and we want to fetch some portion of data for every user running multiple 'tasks' in parallel and then repeat the process. 
```
	private Flux<String> parallelTask(TestWebClient client) {
		return Flux.defer(ReactiveApplication::getUsers)
				.flatMapDelayError(client::request, 10, 1)
				.repeat();
	}

	private Flux<Integer> getUsers() {
		return Flux.range(1, 100);
	}
```

Web client
```
	public Mono<String> request(int context) {
		return webClient.get()
				.uri(uriBuilder -> uriBuilder
						.path("/test")
						.queryParam("ctx", context)
						.build()
				)
				.exchange()
				.transformDeferred(RateLimiterOperator.of(rateLimiter))
				.flatMap(clientResponse -> {
					if (clientResponse.statusCode() == HttpStatus.OK) {
						return clientResponse.bodyToMono(String.class);
					} else {
						return Mono.error(new HttpClientErrorException(clientResponse.statusCode(), clientResponse.toString()));
					}
				})
				.retryWhen(Retry
						.fixedDelay(Long.MAX_VALUE, Duration.ofMillis(5000))
						.doBeforeRetry(retrySignal -> log.warn(retrySignal.toString(), retrySignal.failure()))
				);
	}

	private WebClient webClient(String baseUrl) {
		return WebClient.builder()
				.baseUrl(baseUrl)
				.filter(logRequest())
				.filter(logResponse())
				.build();
	}

	private RateLimiter rateLimiter() {
		RateLimiterConfig config = RateLimiterConfig.custom()
				.limitRefreshPeriod(Duration.ofSeconds(1))
				.limitForPeriod(1)
				.timeoutDuration(Duration.ofSeconds(1))
				.build();

		RateLimiter rateLimiter = RateLimiterRegistry
				.of(config)
				.rateLimiter("web-client");

		return rateLimiter;
	}
```

**Comment by amrynsky** [comment]
Some additional information regarding the topic. The blocking call happens only in case `timeoutDuration` is reached for multiple tasks. Main flow works as expected. 
In our case multiple tasks could be run concurrently and setting `timeoutDuration` to low value doesn't really make sense. It's more protection against too much parallelism. Based on our current understanding `timeoutDuration =~ limitRefreshPeriod * numberOfConcurrentTasks / limitForPeriod`.

**Comment by RobWin** [comment]
It's happening here: https://github.com/resilience4j/resilience4j/blob/9e00e82bfd14f42e23cbbcdf2d10ff2d26e308b1/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/internal/AtomicRateLimiter.java#L185
Backoff strategy is described in this paper: https://arxiv.org/abs/1305.5800

If you really need a non-blocking reactive stream, you currently have to set `timeoutDuration` to 0 and handle retry on the application layer.
If you only want to limit the number of concurrent tasks, you could also use a BulkheadOperator.

**Comment by amrynsky** [comment]
@RobWin thanks for the additional information.

We considered setting  `timeoutDuration` to 0 but according to my current understanding it's not what we are looking for. Basically we are trying to decouple rate limit control from the streams. As I already mentioned we could have multiple streams polling data from the same source at different 'speed' and we want to use  `RateLimiter` to control the 'speed' across multiple streams. 

Looking at current implementation of `RateLimiter` - it's fully reactive till the point when timeout is reached and `rateLimiter.reservePermission()` returns -1.
https://github.com/resilience4j/resilience4j/blob/e0221c7f8897e6e2e4de6726dcc4d39bea415997/resilience4j-reactor/src/main/java/io/github/resilience4j/reactor/ratelimiter/operator/MonoRateLimiter.java#L39-L49

Probably we could set `timeoutDuration` to some large value that in our case would mean unlimited parallelism and control  number of concurrent tasks in some other ways. Will check BulkheadOperator.

**Comment by amrynsky** [comment]
More tests show that increasing number of concurrently running tasks causing this issue from time to time even with large `timeoutDuration`. 

We tried to set `timeoutDuration` to 0, but it resulted in too many `io.github.resilience4j.ratelimiter.RequestNotPermitted` errors that need to be retried and we see `reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park` more often.

@RobWin what is the performance implication of the current implementation for reactive streams? https://github.com/resilience4j/resilience4j/blob/9e00e82bfd14f42e23cbbcdf2d10ff2d26e308b1/resilience4j-ratelimiter/src/main/java/io/github/resilience4j/ratelimiter/internal/AtomicRateLimiter.java#L185

**Comment by RobWin** [comment]
Yes, sry I forgot that I already fixed the blocking waitduration with `Mono.delay` a while ago.
It's only happening in `AtomicRateLimiter.compareAndSet` when there is contention.

**Comment by RobWin** [comment]
See JavaDoc

```
   It differs from {@link AtomicReference#updateAndGet(UnaryOperator)} by
   constant back off. It means that after one try to {@link AtomicReference#compareAndSet(Object,
   Object)} this method will wait for a while before try one more time. This technique was
   originally described in this
   <a href="https://arxiv.org/abs/1305.5800"> paper</a>
   and showed great results with {@link AtomicRateLimiter} in benchmark tests.
```

**Comment by RobWin** [comment]
@storozhukBM Do we really need this backoff?

**Comment by storozhukBM** [comment]
@amrynsky @RobWin 
Yes, this backoff is here to resolve some atomic swap under big contention issues. Our tests show that is increases throughput under contention up to 2 times. On my machine, it goes from 8 permission acquires per microsecond to 14, on machines with more cores gains are even more significant, but this is only necessary for Java 8, starting from version 9 it is already fixed in the JVM itself. 
This `parkNanos` call will not actually "block" your thread, but razer gives OS scheduler a hint to run some other thread else instead and return to it as soon as possible. I think it is totally fine to add our `AtomicRateLimiter.compareAndSet` to BlockHound allow-list. If you take a look at https://github.com/reactor/BlockHound/blob/master/docs/tips.md#how-to-select-what-to-whitelist you can see that our method totally qualifies with this documentation. It does not call any user-provided code, and we know how it will behave and that it will not block worker thread for any prolonged time but would just reschedule itself, and we can safely whitelist it.

**Comment by amrynsky** [comment]
Added `compareAndSet` to whitelist. Here is my configuration for reference
```
BlockHound.install(builder -> builder
		.allowBlockingCallsInside(io.github.resilience4j.ratelimiter.internal.AtomicRateLimiter.class.getName(), "compareAndSet")
);
```

**Comment by amrynsky** [comment]
@RobWin I tried to use `Bulkhead` to achieve the same, but it looks like there is a code that looks really blocking
https://github.com/resilience4j/resilience4j/blob/9ae5db1ed2143f274b02e9b82b9c491f87e0b465/resilience4j-bulkhead/src/main/java/io/github/resilience4j/bulkhead/internal/SemaphoreBulkhead.java#L236
Here is a full call stack

```
reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park}
reactor.blockhound.BlockingOperationError: Blocking call! jdk.internal.misc.Unsafe#park
	at jdk.internal.misc.Unsafe.park(Unsafe.java) ~[?:?]
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:235) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1079) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369) ~[?:?]
	at java.util.concurrent.Semaphore.tryAcquire(Semaphore.java:415) ~[?:?]
	at io.github.resilience4j.bulkhead.internal.SemaphoreBulkhead.tryEnterBulkhead(SemaphoreBulkhead.java:236) ~[resilience4j-bulkhead-1.5.0.jar:1.5.0]
	at io.github.resilience4j.bulkhead.internal.SemaphoreBulkhead.tryAcquirePermission(SemaphoreBulkhead.java:142) ~[resilience4j-bulkhead-1.5.0.jar:1.5.0]
	at io.github.resilience4j.reactor.bulkhead.operator.MonoBulkhead.subscribe(MonoBulkhead.java:36) ~[resilience4j-reactor-1.5.0.jar:1.5.0]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.resubscribe(FluxRetryWhen.java:204) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxRetryWhen$RetryWhenOtherSubscriber.onNext(FluxRetryWhen.java:250) ~[reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:274) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:851) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:241) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:147) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoIgnoreThen$ThenAcceptInner.onNext(MonoIgnoreThen.java:296) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.3.6.RELEASE.jar:3.3.6.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]
```

**Comment by RobWin** [comment]
Yes, we don't have a custom Semaphore which is able to return the wait time.
For Bulkhead and Reactor it is currently recommeneded to set timeout to 0.

**Comment by amrynsky** [comment]
In some scenarios, it would be hard to handle because the client will get an error signal immediately and will need to handle it somehow introducing some delay/backoff. For such scenarios Rate Limiter works much better.
Probably you could close the issue or open another one for `Bulkhead` blocking calls in case there are plans to improve it.  In any case, thanks for your support.
