### ISSUE TITLE
Upgrading to 1.5.0

### ISSUE THREAD

**Issue by shallyyy** [resilience4j/resilience4j#1080]
Resilience4j version: 1.5.0

Java version: 11

When upgrading from 1.2.0 to 1.5.0 we get this error:
```
14:33:19  13:33:18.621 ERROR o.s.boot.SpringApplication - Application run failed
14:33:19  java.lang.IllegalStateException: Error processing condition on io.github.resilience4j.ratelimiter.autoconfigure.RateLimiterConfigurationOnMissingBean.rateLimiterEventsConsumerRegistry
14:33:19  	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:64)
14:33:19  	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
14:33:19  	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:181)
14:33:19  	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:141)
14:33:19  	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
14:33:19  	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327)
14:33:19  	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
14:33:19  	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
14:33:19  	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
14:33:19  	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
14:33:19  	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
14:33:19  	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
14:33:19  	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
14:33:19  	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
14:33:19  	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
14:33:19  	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
14:33:19  	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
14:33:19  	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
14:33:19  	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
14:33:19  	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
14:33:19  	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
```

Our dependencies are:
```
        <dependency>
           <groupId>io.github.resilience4j</groupId>
           <artifactId>resilience4j-spring-boot2</artifactId>
           <version>1.5.0</version>
        </dependency>
        <dependency>
           <groupId>io.github.resilience4j</groupId>
           <artifactId>resilience4j-bulkhead</artifactId>
           <version>1.5.0</version>
        </dependency>
         <dependency>
           <groupId>io.github.resilience4j</groupId>
           <artifactId>resilience4j-circuitbreaker</artifactId>
           <version>1.5.0</version>
        </dependency>
        <dependency>
           <groupId>io.github.resilience4j</groupId>
           <artifactId>resilience4j-retry</artifactId>
           <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-rxjava2</artifactId>
            <version>1.5.0</version>
        </dependency>
```

**Comment by shallyyy** [comment]
> Which Spring Boot 2 version to you use?

:: Spring Boot ::        (v2.1.5.RELEASE)

**Comment by RobWin** [comment]
Resiliencej4 1.5. requires Spring Boot 2.3.X.
Unfortunately you have to try Resilience4j 1.4.X

**Comment by shallyyy** [comment]
Ah cool thanks for the quick replies, will try that out!

**Comment by RobWin** [comment]
Did it work for you?

**Comment by shallyyy** [comment]
Unfortunately we couldn’t update our spring so we settled for resilience 1.4 which did work, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
