### ISSUE TITLE
ConcurrentModificationException warning log while consuming events

### ISSUE THREAD

**Issue by bhochhi** [resilience4j/resilience4j#1115]
Resilience4j version: 1.4.0/1.5.0

Java version: 1.8.0

Following is the warning log I am getting in my prod

```
java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at io.github.resilience4j.core.EventProcessor.processEvent(EventProcessor.java:65)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$CircuitBreakerEventProcessor.consumeEvent(CircuitBreakerStateMachine.java:520)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.publishEventIfPossible(CircuitBreakerStateMachine.java:343)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.publishSuccessEvent(CircuitBreakerStateMachine.java:379)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.onSuccess(CircuitBreakerStateMachine.java:229)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateSupplier$4(CircuitBreaker.java:200)
	at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$2(Retry.java:213)
	at io.github.resilience4j.decorators.Decorators$DecorateSupplier.get(Decorators.java:166)
```

I am using retry and circuit breaker as follows
```
    public Response makeCallWithResilience(String instanceName){ 

            Retry retry = registryService.getRetryRegistry().retry(instanceName);
            CircuitBreaker circuitBreaker = registryService.getCircuitBreakerRegistry.circuitBreaker(instanceName);

            //circuit breaker is chained before retry so that it counts retries into its calculation.
            return Decorators.ofSupplier(() -> callDownstream(url))
                    .withCircuitBreaker(circuitBreaker)
                    .withRetry(retry)
                    .get();
   }
```
registryService is the singleton service that  creates retryRegistry and circuitBreakerRegistry and also initializes retry and circuitBreaker instances on application start. two more lines are subscribing the  `onRetry`, `onRetryError` and `onFailureRateExceeded` just to log the message as follows:

```
public void initOnApplicationLoad(String instanceName){
      this.retryRegistry = RetryRegistry.of(retryConfig);
      this.circuitBreakerRegistry = CircuitBreakerRegistry.of(circuitBreakerConfig);
      
      Retry retry = this.retryRegistry.retry(instanceName);
      retry.getEventPublisher().onRetry(this::handleRetryEvent).onError(this::logMessage);
      
      CircuitBreaker circuitBreaker = this.circuitBreakerRegistry.circuitBreaker(instanceName);
      circuitBreaker.getEventPublisher().onFailureRateExceeded(this::logMessage);
}
```

Here is the unit test to check for concurrency issue to see if I can see any warning.

```
def concurrencyTest(){

        def numberOfThreads = 3000
        ExecutorService service = Executors.newFixedThreadPool(numberOfThreads);
        CountDownLatch latch = new CountDownLatch(1)
        CountDownLatch mainLatch = new CountDownLatch(numberOfThreads)

        when:
        for (int i = 0; i < numberOfThreads; i++) {
            service.submit({
                latch.await() //hold all threads
                makeCallWithResilience("instanceName")
                mainLatch.countDown()
            })
        }
        //release all
        latch.countDown()
    
       mainLatch.await()
       then:
       true
}
```

Unfortunately, not able to reproduce issue in local(i wonder if my test is on sufficient). However in my production, I keep getting about 70 such warning with ConcurrentModificationException. my application serves about 300k requests/hr. 

Definitely there is some sort of race condition, but unable to figure out. I suppose it should have no impact on service call as it seems happening only on event subscription. But I appreciate your help if there is any concern way its implemented(Specially I wanted retry and cb and its order) or any underlying issue with library. 

thank you.
Rupee

**Comment by RobWin** [comment]
Hi,
I seems that some code is adding an another event consumer while the event consumer list of the CircuitBreaker is in use?
You could change your code an register an event consumer when the CircuitBreakerRegistry is created.

You can use the static factory method of the `CircuitBreakerRegistry` or `RetryRegistry` to add a `RegistryEventConsumer`.

```
       List<RegistryEventConsumer<CircuitBreaker>> registryEventConsumers = new ArrayList<>();
        registryEventConsumers.add(new RegistryEventConsumer<CircuitBreaker>() {
            @Override
            public void onEntryAddedEvent(EntryAddedEvent<CircuitBreaker> entryAddedEvent) {
                entryAddedEvent.getAddedEntry().getEventPublisher().onFailureRateExceeded(this::logMessage);
            }

            @Override
            public void onEntryRemovedEvent(EntryRemovedEvent<CircuitBreaker> entryRemoveEvent) {
                // Nothing
            }

            @Override
            public void onEntryReplacedEvent(EntryReplacedEvent<CircuitBreaker> entryReplacedEvent) {
                entryReplacedEvent.getNewEntry().getEventPublisher().onFailureRateExceeded(this::logMessage);
            }
        });

        CircuitBreakerRegistry circuitBreakerRegistry = CircuitBreakerRegistry
            .of(CircuitBreakerConfig.ofDefaults(), registryEventConsumers);
```

**Comment by ra1861** [comment]
Hi!

We have have seen similar exceptions in our run, so I looked at the implementation (EventProcessor.java) and it is obvious (IMHO) 

that it is not a thread-safe implemenation.
There is combination of synchronized methods &  un-synchronized methods, and thread-safe components and non-thread-safe components.
I have made a unit-test to showcase this flaw, please, check it out. It seems to fail everytime.

```
    @Test(expected = ExecutionException.class)
    public void testOnEventParallel() throws ExecutionException {
        EventProcessor<Number> eventProcessor = new EventProcessor<>();
        EventConsumer<Integer> eventConsumer1 = event -> {
            System.out.println("1" + "start" + event.toString());
            try {
                Thread.sleep(10 * 1000L);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            System.out.println("1" + "end" + event.toString());
        };
        EventConsumer<Integer> eventConsumer2 = event -> System.out.println("2" + event.toString());


        eventProcessor.registerConsumer(Integer.class.getSimpleName(), eventConsumer1);

        CompletableFuture<Void> future = CompletableFuture.runAsync(() -> {
            eventProcessor.processEvent(1); // sleeps 10 sec inside
        });
        try {
            Thread.sleep(1 * 1000L);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        eventProcessor.registerConsumer(Integer.class.getSimpleName(), eventConsumer2);

        try {
            future.get();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (ExecutionException e) {
            e.printStackTrace();
            throw e;
        }
    }
```

[EventProcessorTest-patch.txt](https://github.com/resilience4j/resilience4j/files/5096989/EventProcessorTest-patch.txt)

**Comment by RobWin** [comment]
Thanks for the investigation @rulle-io
