### ISSUE TITLE
Problem with registering metrics for more than one circuit breaker

### ISSUE THREAD

**Issue by pruchno** [resilience4j/resilience4j#1131]
Resilience4j version: 1.5.0

Java version: 11

I have got following error while starting my app:
> Caused by: java.lang.IllegalArgumentException: A metric named resilience4j.circuitbreakernot.permitted.calls already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
	at io.micrometer.core.instrument.dropwizard.DropwizardMeterRegistry.newCounter(DropwizardMeterRegistry.java:76)
	at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:522)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:576)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:529)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:522)
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:245)
	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:128)
	at io.micrometer.core.instrument.composite.CompositeCounter.registerNewMeter(CompositeCounter.java:50)
	at io.micrometer.core.instrument.composite.CompositeCounter.registerNewMeter(CompositeCounter.java:23)
	at io.micrometer.core.instrument.composite.AbstractCompositeMeter.add(AbstractCompositeMeter.java:66)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5527)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$0(CompositeMeterRegistry.java:65)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lock(CompositeMeterRegistry.java:184)
	at io.micrometer.core.instrument.composite.CompositeMeterRegistry.lambda$new$1(CompositeMeterRegistry.java:65)
	at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:585)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:529)
	at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:522)
	at io.micrometer.core.instrument.MeterRegistry.counter(MeterRegistry.java:245)
	at io.micrometer.core.instrument.Counter$Builder.register(Counter.java:128)
	at io.github.resilience4j.micrometer.tagged.AbstractCircuitBreakerMetrics.registerMetrics(AbstractCircuitBreakerMetrics.java:138)
	at io.github.resilience4j.micrometer.tagged.AbstractCircuitBreakerMetrics.addMetrics(AbstractCircuitBreakerMetrics.java:50)
	at io.github.resilience4j.micrometer.tagged.TaggedCircuitBreakerMetricsPublisher.publishMetrics(TaggedCircuitBreakerMetricsPublisher.java:48)
	at io.github.resilience4j.micrometer.tagged.TaggedCircuitBreakerMetricsPublisher.publishMetrics(TaggedCircuitBreakerMetricsPublisher.java:25)
	at io.github.resilience4j.core.metrics.MetricsPublisher.onEntryAddedEvent(MetricsPublisher.java:32)
	at io.github.resilience4j.core.registry.CompositeRegistryEventConsumer.lambda$onEntryAddedEvent$0(CompositeRegistryEventConsumer.java:34)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.github.resilience4j.core.registry.CompositeRegistryEventConsumer.onEntryAddedEvent(CompositeRegistryEventConsumer.java:34)
	at io.github.resilience4j.core.EventProcessor.lambda$processEvent$2(EventProcessor.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at io.github.resilience4j.core.EventProcessor.processEvent(EventProcessor.java:65)
	at io.github.resilience4j.core.registry.AbstractRegistry.lambda$computeIfAbsent$0(AbstractRegistry.java:104)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.github.resilience4j.core.registry.InMemoryRegistryStore.computeIfAbsent(InMemoryRegistryStore.java:41)
	at io.github.resilience4j.core.registry.AbstractRegistry.computeIfAbsent(AbstractRegistry.java:102)
	at io.github.resilience4j.circuitbreaker.internal.InMemoryCircuitBreakerRegistry.circuitBreaker(InMemoryCircuitBreakerRegistry.java:166)
	at io.github.resilience4j.circuitbreaker.internal.InMemoryCircuitBreakerRegistry.circuitBreaker(InMemoryCircuitBreakerRegistry.java:160)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration.lambda$initCircuitBreakerRegistry$1(CircuitBreakerConfiguration.java:158)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration.initCircuitBreakerRegistry(CircuitBreakerConfiguration.java:157)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerConfiguration.circuitBreakerRegistry(CircuitBreakerConfiguration.java:78)
	at io.github.resilience4j.circuitbreaker.autoconfigure.AbstractCircuitBreakerConfigurationOnMissingBean.circuitBreakerRegistry(AbstractCircuitBreakerConfigurationOnMissingBean.java:70)
	at io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$32077fa3.CGLIB$circuitBreakerRegistry$6(<generated>)
	at io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$32077fa3$$FastClassBySpringCGLIB$$c7f5237e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$32077fa3.circuitBreakerRegistry(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 70 common frames omitted

This problem occurs for more than one circuit breaker and I assume it's caused due to wrongly built name of metric - '.' is missing in name.

**Comment by RobWin** [comment]
Hi,
could you show me your config?
Did you register the same CircuitBreaker instance twice?

**Comment by RobWin** [comment]
True. The name is wrong. Seems to be a bug in 1.5.0

**Comment by RobWin** [comment]
But this shouldn't cause an issue, because the name of the CircuitBreaker is a tag.

**Comment by pruchno** [comment]
My config:
`resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException$NotFound
    instances:
      user:
        baseConfig: default
      preferences:
        baseConfig: default
      delivery:
        baseConfig: default
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 0
        enableExponentialBackoff: false
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.net.SocketTimeoutException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
    instances:
      user:
        baseConfig: default
      preferences:
        baseConfig: default
      delivery:
        baseConfig: default`

**Comment by RobWin** [comment]
Ok, that's strange. 
Because above we can see that the MeterId of the Counter contains tags:
`MeterId{name='resilience4j.circuitbreakernot.permitted.calls', tags=[tag(kind=not_permitted),tag(name=delivery)]}`

The name `resilience4j.circuitbreaker.{name}.calls.{kind}` of the `Timer` is not created by us. It seems Micrometer modifies the name and adds tag placeholders?
But why does it not add the placeholders to the `Counter`?

**Comment by RobWin** [comment]
I run the unit test and investigate it.

**Comment by RobWin** [comment]
In my unit test I can't replicate your observation. The name of the Timer does not contain any placeholders.

![image](https://user-images.githubusercontent.com/5815046/90725585-b36bb500-e2c0-11ea-9e31-928294662eb7.png)

**Comment by pruchno** [comment]
The second timer is going to be registered with the same name? Will this be a problem? What version of micrometer do you have there?

**Comment by RobWin** [comment]
We use v1.5.1 -> https://github.com/resilience4j/resilience4j/blob/master/libraries.gradle#L28

**Comment by RobWin** [comment]
Yes it has the same name, but the MeterId is a class which is composed of the name and tags. That means the name must not be unique.

**Comment by pruchno** [comment]
What implementation of MeterRegistry you use in your unit tests? Maybe DropwizardMeterRegistry?

**Comment by RobWin** [comment]
SimpleMeterRegistry

**Comment by pruchno** [comment]
Ok, now I have a clear pictture. So the problem with registering metrics is on my side.

**Comment by RobWin** [comment]
Can we close the issue?
