### ISSUE TITLE
resilience4j cloud2 throws NoSuchFieldError

### ISSUE THREAD

**Issue by dnguyen-gc** [resilience4j/resilience4j#1151]
Resilience4j version: 1.5.0
Java version: 11

I use resilience4j annotation @CircuitBreaker

I noticed resilience4j.cloud2 1.5.0 brings in circuit breaker 1.3.1

I see the following error:

```
[WARN ] 2020-09-02 14:07:26.298 [DiscoveryClient-InstanceInfoReplicator-0] InstanceInfoReplicator - There was a problem with the instance info replicator
java.lang.NoSuchFieldError: entryMap
	at io.github.resilience4j.circuitbreaker.internal.InMemoryCircuitBreakerRegistry.getAllCircuitBreakers(InMemoryCircuitBreakerRegistry.java:127) ~[resilience4j-circuitbreaker-1.3.1.jar:1.3.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:499) ~[spring-cloud-context-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at com.sun.proxy.$Proxy212.getAllCircuitBreakers(Unknown Source) ~[?:?]
	at io.github.resilience4j.circuitbreaker.monitoring.health.CircuitBreakersHealthIndicator.health(CircuitBreakersHealthIndicator.java:105) ~[resilience4j-spring-boot2-1.5.0.jar:1.5.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1675) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:195) ~[spring-cloud-netflix-eureka-client-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:176) ~[spring-cloud-netflix-eureka-client-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:170) ~[spring-cloud-netflix-eureka-client-2.2.4.RELEASE.jar:2.2.4.RELEASE]
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1442) ~[eureka-client-1.9.25.jar:1.9.25]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117) ~[eureka-client-1.9.25.jar:1.9.25]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

But when I don't use cloud2 but import each and every module e.g CB, Retry, TimeLimiter, etc.. The problem doesn't exist. 

Why resilience4j cloud2 version 1.5.0 brings in CB 1.3.1 ?

**Comment by RobWin** [comment]
Maybe it's a transitive dependency of your Spring Cloud BOM which overrides our v1.5.0.
Are you using the Spring Cloud BOM?

**Comment by Romeh** [comment]
an example of for dependency management version conflict resolution between spring cloud circuit breaker starter and resilience4j here  : https://github.com/Romeh/spring-cloud-gateway-resilience4j/blob/master/pom.xml

**Comment by cmhdave** [comment]
I'm having this problem too so on a whim I dropped the version of resilience4j that I'm pulling in down to 1.4.0 and it's the same issue with that version.  We are using Spring Boot 2.3.2.RELEASE
