### ISSUE TITLE
resilience4j circut breaker not working with coroutines

### ISSUE THREAD

**Issue by dejewskipiotr** [resilience4j/resilience4j#1267]
Resilience4j version: 1.6.1

Java version: 11

I am trying to setup resilience4j circuit breaker with coroutines application. I am using default configuration of circuit breaker.

    suspend fun function(request: ServerRequest): ServerResponse {
        for (i in 0..300) {
            try {
                CircuitBreaker.ofDefaults("default").executeSuspendFunction {
                    log.error("$i")
                    throw Exception("e$i")
                }
            } catch (e: Exception) {
                log.error("${e.message} ${e::class.java}")
            }
        }
        return ServerResponse.status(HttpStatus.OK).bodyValueAndAwait("")
    }
After running this code i get Excetion 300 times. If I understand it correctly, with default configuration i should get Exception 100 times and then CallNotPermittedException but it is not happenning. Am i using it correctly?

in logs i can see lot of logs similiar to this one:
```
2020-12-11 11:25:24.329 DEBUG 12888 --- [ctor-http-nio-3] i.g.r.c.i.CircuitBreakerStateMachine     : CircuitBreaker 'default' recorded an exception as failure:

java.lang.Exception: e300
	at com.example.demo.ServiceA$function$2.invokeSuspend(ServiceA.kt:22) ~[main/:na]
	at com.example.demo.ServiceA$function$2.invoke(ServiceA.kt) ~[main/:na]
	at io.github.resilience4j.kotlin.circuitbreaker.CircuitBreakerKt.executeSuspendFunction(CircuitBreaker.kt:33) ~[resilience4j-kotlin-1.6.1.jar:1.6.1]
	at com.example.demo.ServiceA.function$suspendImpl(ServiceA.kt:20) ~[main/:na]
	at com.example.demo.ServiceA.function(ServiceA.kt) ~[main/:na]
	at com.example.demo.AuthRoutes$authRouterFunction$1$1.invoke(Routes.kt:15) ~[main/:na]
	at com.example.demo.AuthRoutes$authRouterFunction$1$1.invoke(Routes.kt:9) ~[main/:na]
```

**Comment by dejewskipiotr** [comment]
I figured it out. I was using differrent circuit breaker every time.
