### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by JoyceDoctor** [resilience4j/resilience4j#1344]
Hi,
I am using Spring boot 2.3.6.RELEASE.

First, I have two sides. side A and side B both hosting the same SOAP Service.
If I am able to execute the Soap service on side A then there is no need to execute side B. But if site A failed like I give it a wrong IP address then it should execute the soap service on side B. 

I am implementing ClientInterceptor handleFault to handle soap fault message and afterCompletion function. handleFault  function is working cause I can see the soap fault message. 

I added debugging log in afterCompletion as shown below:
	@Override
	public void afterCompletion(MessageContext arg0, Exception arg1) throws WebServiceClientException {
		// TODO Auto-generated method stub
		
		log.info("afterCompletion..");
		log.info("arg1:{}", arg1.getMessage());
		log.info("response:{}", arg0.getResponse());
	}

First test -- Site A IP is valid:
I am using getWebServiceTemplate to execute Soap service and I am getting the result which is what I am expected. So there is no need to execute site B.

Second test -- site A IP is invalid and site B IP is valid:

Now I can see the log traces in the afterCompletion function:

I can see the logging:
2021-02-19 15:09:02.521  INFO 5708 --- [nio-8080-exec-1] g.i.f.s.i.YYYSecurityInterceptor         : afterCompletion..
2021-02-19 15:09:02.522  INFO 5708 --- [nio-8080-exec-1] g.i.f.s.i.YYYSecurityInterceptor         : arg1:connect timed out
2021-02-19 15:09:02.523  INFO 5708 --- [nio-8080-exec-1] g.i.f.s.i.YYYSecurityInterceptor         : response:SaajSoapMessage

Now I expected that site A will failed but not site B. Below is the exception for site A.

https://github.com/spring-projects/spring-ws/blob/ec692a945b1787f650c6023a0c3621b427440ca3/spring-ws-core/src/main/java/org/springframework/ws/transport/support/TransportUtils.java#L31

First line in the exception, Could not close the WeServiceConnection. It is coming blog above.

2021-02-19 15:08:56.507 DEBUG 5708 --- [nio-8080-exec-1] o.s.ws.transport.support.TransportUtils  : Could not close WebServiceConnection

java.net.SocketTimeoutException: connect timed out
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_45]
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_45]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_45]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_45]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_45]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_45]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_45]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_45]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:656) ~[na:1.8.0_45]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_45]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_45]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282) ~[na:1.8.0_45]
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257) ~[na:1.8.0_45]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[na:1.8.0_45]
        at org.springframework.ws.transport.http.HttpUrlConnection.getRequestOutputStream(HttpUrlConnection.java:89) ~[spring-ws-core-3.0.10.RELEASE.jar:na]
        at org.springframework.ws.transport.AbstractSenderConnection$RequestTransportOutputStream.createOutputStream(AbstractSenderConnection.java:87) ~[spring-ws-core-3.0.10.RELEASE.jar:na]
        at org.springframework.ws.transport.TransportOutputStream.getOutputStream(TransportOutputStream.java:41) ~[spring-ws-core-3.0.10.RELEASE.jar:na]
        at org.springframework.ws.transport.TransportOutputStream.close(TransportOutputStream.java:49) ~[spring-ws-core-3.0.10.RELEASE.jar:na]
        at org.springframework.ws.transport.AbstractWebServiceConnection.close(AbstractWebServiceConnection.java:141) ~[spring-ws-core-3.0.10.RELEASE.jar:na]
        at org.springframework.ws.transport.support.TransportUtils.closeConnection(TransportUtils.java:45) ~[spring-ws-core-3.0.10.RELEASE.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:564) [spring-ws-core-3.0.10.RELEASE.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.marshalSendAndReceive(WebServiceTemplate.java:390) [spring-ws-core-3.0.10.RELEASE.jar:na]

	<**** internal codes deleted sorry not even the package name ***>

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) [tomcat-embed-core-9.0.39.jar:4.0.FR]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [tomcat-embed-core-9.0.39.jar:4.0.FR]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.3.6.RELEASE.jar:2.3.6.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.39.jar:9.0.39]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]

2021-02-19 15:08:56.510  INFO 5708 --- [nio-8080-exec-1] *******  : WebServiceClientException:I/O error: connect timed out; nested exception is java.net.SocketTimeoutException: connect timed out

The above exception is for the site A. Site B exception is also the same -- timeout.

Below is the codes that I am using to execute the SOAP service. 

		// create getuser soap envelope
		JAXBElement<GetXXXReq> jaxbElementGetXXXReq = factory.createGetUser(getXXXRequest);

					// execute the request using the formatted URL.
					JAXBElement<GetXXXRes> apiResponse = (JAXBElement<GetXXXRes>) getWebServiceTemplate()
							.marshalSendAndReceive(url, jaxbElementGetXXXReq, createWebServiceMessageCallback(authHeader));

Connection time out is happening when the I execute the statement above.

Do I need to execute delay before the next getWebServiceTemplate() request?

Since it the statement below failed. I am assuming that the connection was not opened in the first place.
2021-02-19 15:08:56.507 DEBUG 5708 --- [nio-8080-exec-1] o.s.ws.transport.support.TransportUtils  : Could not close WebServiceConnection

Any idea why I am getting Connection timeout when the URL is correct?

Thanks.

Joyce

**Comment by Romeh** [comment]
@JoyceDoctor  I do not understand why this is created here on resilience4j , i see nothing related into the description to the library we support here , are you sure u are writing to the write project ?
