### ISSUE TITLE
Spring Boot 2.4.3 and Resilience4j 1.7.0

### ISSUE THREAD

**Issue by mortezalatifi** [resilience4j/resilience4j#1361]
Resilience4j version: io.github.resilience4j:resilience4j-spring-boot2:1.7.0
Spring Boot version: 2.4.3

After Upgrading to Spring Boot 2.4.3, I get this Error Message:

`java.lang.IllegalStateException: Failed to introspect Class [io.github.resilience4j.retry.autoconfigure.AbstractRetryConfigurationOnMissingBean] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@2c13da15]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:371) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:414) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$2(AbstractAutowireCapableBeanFactory.java:747) ~[spring-beans-5.3.4.jar:5.3.4]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737) ~[na:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:746) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:685) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:656) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1670) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:570) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:542) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:667) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:659) ~[spring-beans-5.3.4.jar:5.3.4]
	at org.springframework.context.support.AbstractApplicationContext.getBeansOfType(AbstractApplicationContext.java:1299) ~[spring-context-5.3.4.jar:5.3.4]
	at org.springframework.boot.SpringApplication.getExitCodeFromMappedException(SpringApplication.java:899) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.getExitCodeFromException(SpringApplication.java:887) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.handleExitCode(SpringApplication.java:874) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:815) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:336) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.3.jar:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.3.jar:2.4.3]
	at com.example.client.ClientApplicationKt.main(ClientApplication.kt:18) ~[main/:na]
Caused by: java.lang.NoClassDefFoundError: io/github/resilience4j/core/ContextAwareScheduledThreadPoolExecutor
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.4.jar:5.3.4]
	... 22 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.github.resilience4j.core.ContextAwareScheduledThreadPoolExecutor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
	... 26 common frames omitted`

Thats how my dependencies look like:
![Bildschirmfoto 2021-03-03 um 11 19 20](https://user-images.githubusercontent.com/27232829/109791120-63c45980-7c12-11eb-89fd-fa89c6502c84.png)

Changing to io.github.resilience4j:resilience4j-spring-boot2:1.6.1 works fine.

Adding resilience4j-core causes an other error...

Is it possible to use resilience4j-spring-boot2:1.7.0 with spring boot 2.4.3?

**Comment by Romeh** [comment]
you need to align your resilience4j versions for all resilience4j dependencies , you can not mix 1.6.1 with 1.7.0 , so either u have all based into 1.7.0 or 1.6.1

**Comment by chas678** [comment]
They are mixed - spring-boot-2 at 1.7.0 is still built on 1.6.1 for transitive dependencies. `mvn dependency:tree -Dverbose "-Dincludes=*:resilience4j-circuitbreaker"`

`[INFO] \- io.github.resilience4j:resilience4j-spring-boot2:jar:1.7.0:compile
[INFO]    \- io.github.resilience4j:resilience4j-spring:jar:1.6.1:compile (version managed from 1.7.0)
[INFO]       \- io.github.resilience4j:resilience4j-framework-common:jar:1.6.1:compile
[INFO]          \- io.github.resilience4j:resilience4j-circuitbreaker:jar:1.6.1:compile`

**Comment by mortezalatifi** [comment]
Yes exactly. I have pinned the version (1.7.0) by each sub-dependecy of the spring-boot2 and it works.

`    implementation("io.github.resilience4j:resilience4j-spring-boot2:1.7.0")
    implementation("io.github.resilience4j:resilience4j-spring:1.7.0")
    implementation("io.github.resilience4j:resilience4j-timelimiter:1.7.0")
    implementation("io.github.resilience4j:resilience4j-retry:1.7.0")
    implementation("io.github.resilience4j:resilience4j-ratelimiter:1.7.0")
    implementation("io.github.resilience4j:resilience4j-micrometer:1.7.0")
    implementation("io.github.resilience4j:resilience4j-core:1.7.0")
    implementation("io.github.resilience4j:resilience4j-consumer:1.7.0")
    implementation("io.github.resilience4j:resilience4j-circularbuffer:1.7.0")
    implementation("io.github.resilience4j:resilience4j-circuitbreaker:1.7.0")
    implementation("io.github.resilience4j:resilience4j-bulkhead:1.7.0")
    implementation("io.github.resilience4j:resilience4j-annotations:1.7.0")`

**Comment by chas678** [comment]
actually - Thinking about it in my example, it could be spring-cloud that is version pinning 1.6.1 of resilience4j-spring - so pinning to 1.7.0 of all the dependencies is probably the correct thing to do.  Its a shame there isn't a BOM to do them all though.

**Comment by Romeh** [comment]
@chas678 
You can create a ticket to spring cloud starter about it meanwhile for reilience4j we have our BOM for it here for maven for example:
https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-bom/1.7.0
