### ISSUE TITLE
Failed to load test applicationContext

### ISSUE THREAD

**Issue by beckonpraveen** [resilience4j/resilience4j#1507]
Resilience4j version: 1.7.0

Java version: 1.8

Spring boot version: 2.1.6.RELEASE

Hey Team,

I have integrated resilience4j-spring-boot2 and have no issues with the application runtime, but running into issues when i run the tests, where the applicationContext fails to load
```
2021-07-29 21:09:50.111  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.bulkhead.autoconfigure.BulkheadMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$7c05af72: java.lang.ArrayStoreException
2021-07-29 21:09:50.112  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.bulkhead.autoconfigure.ThreadPoolBulkheadMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$34b090d8: java.lang.ArrayStoreException
2021-07-29 21:09:50.113  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$3f886cb2: java.lang.ArrayStoreException
2021-07-29 21:09:50.113  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.ratelimiter.autoconfigure.RateLimiterMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$35079938: java.lang.ArrayStoreException
2021-07-29 21:09:50.114  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.retry.autoconfigure.RetryMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$ecaf6158: java.lang.ArrayStoreException
2021-07-29 21:09:50.115  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.timelimiter.autoconfigure.TimeLimiterMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$81b32f1e: java.lang.ArrayStoreException
2021-07-29 21:09:50.598  INFO 94350 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-07-29 21:09:50.622  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.bulkhead.autoconfigure.BulkheadMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$7c05af72: java.lang.ArrayStoreException
2021-07-29 21:09:50.622  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.bulkhead.autoconfigure.ThreadPoolBulkheadMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$34b090d8: java.lang.ArrayStoreException
2021-07-29 21:09:50.622  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.circuitbreaker.autoconfigure.CircuitBreakerMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$3f886cb2: java.lang.ArrayStoreException
2021-07-29 21:09:50.623  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.ratelimiter.autoconfigure.RateLimiterMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$35079938: java.lang.ArrayStoreException
2021-07-29 21:09:50.623  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.retry.autoconfigure.RetryMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$ecaf6158: java.lang.ArrayStoreException
2021-07-29 21:09:50.624  INFO 94350 --- [           main] o.s.core.annotation.AnnotationUtils      : Failed to introspect annotations on class io.github.resilience4j.timelimiter.autoconfigure.TimeLimiterMetricsAutoConfiguration$$EnhancerBySpringCGLIB$$81b32f1e: java.lang.ArrayStoreException
2021-07-29 21:09:50.636  WARN 94350 --- [           main] aWebConfiguration$JpaWebMvcConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2021-07-29 21:09:50.665  WARN 94350 --- [           main] o.s.w.c.s.GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException
```

```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]: Invocation of init method failed; nested exception is java.lang.ArrayStoreException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:119)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 24 more
Caused by: java.lang.ArrayStoreException
```

import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class TestApplication {
}

i have included the below dependencies

```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
            <scope>compile</scope>
        </dependency>
  <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-all</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-reactor</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.resilience4j</groupId>
            <artifactId>resilience4j-spring-boot2</artifactId>
            <version>${resilience4j.version}</version>
        </dependency>

```
would really appreciate any help here, please let me know if i should add more details

Thanks,
Praveen

**Comment by RobWin** [comment]
I've never seen this error before. Are you sure it's related to resilience4j?
