### ISSUE TITLE
Question: Getting Thread was interrupted while getting permission

### ISSUE THREAD

**Issue by rahul-aerospike** [resilience4j/resilience4j#1521]
Resilience4j version: "io.github.resilience4j" % "resilience4j-all" % "1.7.0",

Java version: 1.8
scala : 2.12.11
spark: 3.0.3

My use case is to limit write rate of spark using resilience4j

Ratelimiter config
```
RateLimiterConfig
          .custom()
          .limitRefreshPeriod(Duration.ofSeconds(1)) //per second
          .limitForPeriod(config.getWritePerSecond)
          .timeoutDuration(Duration.ofDays(1)) //timeout for blocked task is high because we do not how long backoff will delay.
          .writableStackTraceEnabled(true)
          .build()
```
Implementation code 

```
//This object is just created once
class Writer() extends DataWriter[InternalRow]{
 
   //initialization and stuff ...
   // WriteUtility.syncWriteRow()...  returns a future 
   //constructed 

   //this method is repetitively called by spark to write records
   override def write(row: InternalRow): Unit =  {

    val future=
      (rateLimiterConfig.isDefined , retry.isDefined) match {
        case (true, true) => Decorators
          .ofSupplier(() => WriteUtility.syncWriteRow(row, ...))
          .withRateLimiter(rateLimiterConfig.get).withRetry(retry.get).get()
        case (false, true) => Decorators
          .ofSupplier( () => WriteUtility.syncWriteRow(row, ...))
          .withRetry(retry.get).get()
        case (true, false) =>
        //here if the permit is available I was expecting that function will be blocked until a new permit available
          Decorators
            .ofSupplier(() => WriteUtility.syncWriteRow(row, ...))
            .withRateLimiter(rateLimiterConfig.get)
            .get()

        case (false, false) => WriteUtility.syncWriteRow(row, ...))
      }
    submittedFutures +=future
  }
}
```

I'm getting following exception consistently
```
o.github.resilience4j.core.exception.AcquirePermissionCancelledException: Thread was interrupted while waiting for a permission
	at io.github.resilience4j.ratelimiter.RateLimiter.waitForPermission(RateLimiter.java:588)
	at io.github.resilience4j.ratelimiter.RateLimiter.lambda$decorateCheckedSupplier$9076412b$1(RateLimiter.java:213)
	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
	at io.vavr.Function0.get(Function0.java:149)
	at io.github.resilience4j.decorators.Decorators$DecorateSupplier.get(Decorators.java:166)
	at com.aerospike.spark.sql.sources.v2.AerospikeBatchWriter.write(AerospikeBatchWriter.scala:66)
	at com.aerospike.spark.sql.sources.v2.AerospikeBatchWriter.write(AerospikeBatchWriter.scala:25)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$7(WriteToDataSourceV2Exec.scala:441)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:477)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:385)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:463)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Any thoughts why I'm getting this?

**Comment by ljluestc** [comment]
```
import io.github.resilience4j.decorators.Decorators
import io.github.resilience4j.ratelimiter.RateLimiterConfig
import scala.concurrent.Future

class Writer(rateLimiterConfig: Option[RateLimiterConfig], retry: Option[RetryConfig]) extends DataWriter[InternalRow] {
  override def write(row: InternalRow): Unit =  {
    val future = (rateLimiterConfig.isDefined, retry.isDefined) match {
      case (true, true) => Decorators
        .ofSupplier(() => WriteUtility.syncWriteRow(row, ...))
        .withRateLimiter(rateLimiterConfig.get)
        .withRetry(retry.get)
        .get()
      case (false, true) => Decorators
        .ofSupplier(() => WriteUtility.syncWriteRow(row, ...))
        .withRetry(retry.get)
        .get()
      case (true, false) => Decorators
        .ofSupplier(() => WriteUtility.syncWriteRow(row, ...))
        .withRateLimiter(rateLimiterConfig.get)
        .get()
      case (false, false) => Future.successful(WriteUtility.syncWriteRow(row, ...)) // No rate limiter or retry
    }
    submittedFutures += future
  }
}

```
