### ISSUE TITLE
spring cloud ignore exception issue

### ISSUE THREAD

**Issue by himanshumps** [resilience4j/resilience4j#1538]
Resilience4j version: 1.7.0

Java version: 11

I have the following configuration

```
@Configuration
public class CircuitBreakers
{
  /**
   * Couchbase get circuit breaker
   * @return The {@link CircuitBreakerConstants#COUCHBASE_GET_CIRCUIT_BREAKER} circuit breaker
   */
  @Bean
  public Customizer<ReactiveResilience4JCircuitBreakerFactory> couchbaseGetCircuitBreakerCustomizer() {
    return factory -> {
      factory.configure(builder -> builder
              .timeLimiterConfig(TimeLimiterConfig.custom().timeoutDuration(Duration.ofMillis(2500)).build())
              .circuitBreakerConfig(CircuitBreakerConfig.custom()
                      .minimumNumberOfCalls(1)      //minimum number of call to be made in order to open the circuit
                      .permittedNumberOfCallsInHalfOpenState(1)
                      .enableAutomaticTransitionFromOpenToHalfOpen()
                      .ignoreExceptions(DocumentNotFoundException.class, NoSuchElementException.class)
                      .waitIntervalFunctionInOpenState(IntervalFunction.ofExponentialBackoff(Duration.ofMinutes(2), 2, Duration.ofHours(4)))
                      .build()),
              CircuitBreakerConstants.COUCHBASE_GET_CIRCUIT_BREAKER);
    };
  }
}
```

I have the get call that is decorated by circuit breaker

```
@Component
@Slf4j
public class CouchbaseRead {
  @Autowired
  @Qualifier(value = BeanNames.REACTIVE_COUCHBASE_TEMPLATE)
  ReactiveCouchbaseTemplate primaryReactiveCouchbaseTemplate;

  @Autowired
  @Qualifier(value = "secondaryCouchbaseReactiveTemplate")
  ReactiveCouchbaseTemplate secondaryCouchbaseReactiveTemplate;

  @Autowired
  private ReactiveCircuitBreakerFactory reactiveCircuitBreakerFactory;

  /**
   * Get the GetResult for the given ID with the circuitbreaker
   *
   * @param id The ID to search
   * @return The GetResult Object having all the details about the id
   */
  public Mono<GetResult> getResult(String id) {
    ReactiveCircuitBreaker couchbaseGetCircuitBreaker = reactiveCircuitBreakerFactory.create(CircuitBreakerConstants.COUCHBASE_GET_CIRCUIT_BREAKER);
    return Mono.defer(() -> primaryReactiveCouchbaseTemplate
                    .getCouchbaseClientFactory()
                    .withScope(CollectionIdentifier.DEFAULT_SCOPE)
                    .getCollection(CollectionIdentifier.DEFAULT_COLLECTION)
                    .reactive()
                    .get(id)
                    .doOnEach(s -> {
                      if (s.isOnNext()) {
                        log.info("Success while calling get from reactiveCouchbaseTemplate");
                      } else if (s.isOnError()) {
                        log.error("Failure while calling get from reactiveCouchbaseTemplate", s.getThrowable());
                      }
                    })
            )
            .transform(it -> {
              return couchbaseGetCircuitBreaker.run(it, throwable -> Mono.<GetResult>defer(() -> secondaryCouchbaseReactiveTemplate
                      .getCouchbaseClientFactory()
                      .withScope(CollectionIdentifier.DEFAULT_SCOPE)
                      .getCollection(CollectionIdentifier.DEFAULT_COLLECTION)
                      .reactive()
                      .get(id)
                      .doOnEach(s -> {
                        if (s.isOnNext()) {
                          log.info("Success while calling get from secondaryCouchbaseReactiveTemplate");
                        } else if (s.isOnError()) {
                          log.error("Failure while calling get from secondaryCouchbaseReactiveTemplate", s.getThrowable());
                        }
                      })));
            });
  }
}
```
When I call the above method, the fallback method is also getting executed (Refer this line "Failure while calling get from secondaryCouchbaseReactiveTemplate"), even though the first function throws DocumentNotFoundException which is in ignore list

```
2021-09-13 23:10:12.738 ERROR 25012 --- [   cb-io-kv-5-4] c.a.p.e.p.nosql.couchbase.CouchbaseRead  : Failure while calling get from reactiveCouchbaseTemplate

com.couchbase.client.core.error.DocumentNotFoundException: Document with the given id not found {"completed":true,"coreId":"0x77a19ff600000001","idempotent":true,"lastChannelId":"77A19FF600000001/000000009B7D44A7","lastDispatchedFrom":"172.24.40.209:63425","lastDispatchedTo":"lpdospdbb50431.phx.tttt.com:11210","requestId":4929,"requestType":"GetRequest","retried":0,"service":{"bucket":"pricing-engine","collection":"_default","documentId":"HEALTHCHECK10","opaque":"0x13a2","scope":"_default","type":"kv"},"status":"NOT_FOUND","timeoutMs":2500,"timings":{"dispatchMicros":312981,"totalDispatchMicros":312981,"totalServerMicros":0,"totalMicros":314076,"serverMicros":0}}
	at com.couchbase.client.core.error.DefaultErrorUtil.keyValueStatusToException(DefaultErrorUtil.java:45) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.java.kv.GetAccessor.lambda$get$0(GetAccessor.java:60) ~[java-client-3.2.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at com.couchbase.client.core.msg.BaseRequest.succeed(BaseRequest.java:150) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decodeAndComplete(KeyValueMessageHandler.java:384) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decode(KeyValueMessageHandler.java:363) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.channelRead(KeyValueMessageHandler.java:286) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.MemcacheProtocolVerificationHandler.channelRead(MemcacheProtocolVerificationHandler.java:85) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[core-io-2.2.1.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2021-09-13 23:10:12.738 DEBUG 25012 --- [   cb-io-kv-5-4] i.g.r.c.i.CircuitBreakerStateMachine     : CircuitBreaker 'COUCHBASE_GET_CIRCUIT_BREAKER' ignored an exception:

com.couchbase.client.core.error.DocumentNotFoundException: Document with the given id not found {"completed":true,"coreId":"0x77a19ff600000001","idempotent":true,"lastChannelId":"77A19FF600000001/000000009B7D44A7","lastDispatchedFrom":"172.24.40.209:63425","lastDispatchedTo":"lpdospdbb50431.phx.tttt.com:11210","requestId":4929,"requestType":"GetRequest","retried":0,"service":{"bucket":"pricing-engine","collection":"_default","documentId":"HEALTHCHECK10","opaque":"0x13a2","scope":"_default","type":"kv"},"status":"NOT_FOUND","timeoutMs":2500,"timings":{"dispatchMicros":312981,"totalDispatchMicros":312981,"totalServerMicros":0,"totalMicros":314076,"serverMicros":0}}
	at com.couchbase.client.core.error.DefaultErrorUtil.keyValueStatusToException(DefaultErrorUtil.java:45) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.java.kv.GetAccessor.lambda$get$0(GetAccessor.java:60) ~[java-client-3.2.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at com.couchbase.client.core.msg.BaseRequest.succeed(BaseRequest.java:150) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decodeAndComplete(KeyValueMessageHandler.java:384) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decode(KeyValueMessageHandler.java:363) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.channelRead(KeyValueMessageHandler.java:286) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.MemcacheProtocolVerificationHandler.channelRead(MemcacheProtocolVerificationHandler.java:85) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[core-io-2.2.1.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2021-09-13 23:10:12.739 DEBUG 25012 --- [   cb-io-kv-5-4] i.g.r.c.i.CircuitBreakerStateMachine     : Event IGNORED_ERROR published: 2021-09-13T23:10:12.738759100+05:30[Asia/Calcutta]: CircuitBreaker 'COUCHBASE_GET_CIRCUIT_BREAKER' recorded an error which has been ignored: 'com.couchbase.client.core.error.DocumentNotFoundException: Document with the given id not found {"completed":true,"coreId":"0x77a19ff600000001","idempotent":true,"lastChannelId":"77A19FF600000001/000000009B7D44A7","lastDispatchedFrom":"172.24.40.209:63425","lastDispatchedTo":"lpdospdbb50431.phx.tttt.com:11210","requestId":4929,"requestType":"GetRequest","retried":0,"service":{"bucket":"pricing-engine","collection":"_default","documentId":"HEALTHCHECK10","opaque":"0x13a2","scope":"_default","type":"kv"},"status":"NOT_FOUND","timeoutMs":2500,"timings":{"dispatchMicros":312981,"totalDispatchMicros":312981,"totalServerMicros":0,"totalMicros":314076,"serverMicros":0}}'. Elapsed time: 314 ms
2021-09-13 23:10:13.054 ERROR 25012 --- [   cb-io-kv-5-1] c.a.p.e.p.nosql.couchbase.CouchbaseRead  : Failure while calling get from secondaryCouchbaseReactiveTemplate

com.couchbase.client.core.error.DocumentNotFoundException: Document with the given id not found {"completed":true,"coreId":"0x77a19ff600000002","idempotent":true,"lastChannelId":"77A19FF600000002/00000000926E6543","lastDispatchedFrom":"172.24.40.209:63433","lastDispatchedTo":"lpdospdbb50431.phx.tttt.com:11210","requestId":4930,"requestType":"GetRequest","retried":0,"service":{"bucket":"pace","collection":"_default","documentId":"HEALTHCHECK10","opaque":"0x13a3","scope":"_default","type":"kv"},"status":"NOT_FOUND","timeoutMs":2500,"timings":{"dispatchMicros":314047,"totalDispatchMicros":314047,"totalServerMicros":0,"totalMicros":314422,"serverMicros":0}}
	at com.couchbase.client.core.error.DefaultErrorUtil.keyValueStatusToException(DefaultErrorUtil.java:45) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.java.kv.GetAccessor.lambda$get$0(GetAccessor.java:60) ~[java-client-3.2.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[na:na]
	at com.couchbase.client.core.msg.BaseRequest.succeed(BaseRequest.java:150) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decodeAndComplete(KeyValueMessageHandler.java:384) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decode(KeyValueMessageHandler.java:363) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.channelRead(KeyValueMessageHandler.java:286) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.io.netty.kv.MemcacheProtocolVerificationHandler.channelRead(MemcacheProtocolVerificationHandler.java:85) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[core-io-2.2.1.jar:na]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[core-io-2.2.1.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

2021-09-13 23:10:13.058  INFO 25012 --- [ctor-http-nio-4] reactor.netty.http.server.AccessLog      : 0:0:0:0:0:0:0:1 - - [13/Sep/2021:23:10:12 +0530] "GET /pricing-engine/HEALTHCHECK10/details HTTP/1.1" 400 5266 637

```

**Comment by himanshumps** [comment]
@RobWin Something you might want to look at ? May be I am doing something incorrectly

**Comment by RobWin** [comment]
Hi,
you are using Spring Cloud Circuitbreaker which is maintained by the Spring Team not us.

**Comment by himanshu-gupta01** [comment]
Should I raise it with spring team. I thought ignore exception is something specific to resilence4j and you might hae provided input.

**Comment by RobWin** [comment]
Ignoring an exception does not mean that it is catched by the circuitbreaker, but that the error does not increase the failure rate.
The exception is still propagated.
