### ISSUE TITLE
Blockhound shows a blocking call in Timelimiter

### ISSUE THREAD

**Issue by joost-de-vries** [resilience4j/resilience4j#1545]
Resilience4j version: 1.7.0

Java version: 11

When using resilience4j-kotlin and coroutine dispatcher `Dispatchers.Default` we get a `BlockingOperationError`. 

Is this a false positive? 

See stacktrace below:
```
Caused by: reactor.blockhound.BlockingOperationError: Blocking call! java.lang.Thread.onSpinWait
	at java.base/java.lang.Thread.onSpinWait(Thread.java:374) ~[na:na]
	at java.base/java.util.concurrent.locks.StampedLock.acquireWrite(StampedLock.java:1243) ~[na:na]
	at java.base/java.util.concurrent.locks.StampedLock.writeLock(StampedLock.java:461) ~[na:na]
	at io.github.resilience4j.circularbuffer.ConcurrentEvictingQueue.writeConcurrently(ConcurrentEvictingQueue.java:296) ~[resilience4j-circularbuffer-1.7.0.jar:1.7.0]
	at io.github.resilience4j.circularbuffer.ConcurrentEvictingQueue.offer(ConcurrentEvictingQueue.java:133) ~[resilience4j-circularbuffer-1.7.0.jar:1.7.0]
	at io.github.resilience4j.circularbuffer.ConcurrentCircularFifoBuffer.add(ConcurrentCircularFifoBuffer.java:85) ~[resilience4j-circularbuffer-1.7.0.jar:1.7.0]
	at io.github.resilience4j.consumer.CircularEventConsumer.consumeEvent(CircularEventConsumer.java:45) ~[resilience4j-consumer-1.7.0.jar:1.7.0]
	at io.github.resilience4j.core.EventProcessor.lambda$processEvent$1(EventProcessor.java:57) ~[resilience4j-core-1.7.0.jar:1.7.0]
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807) ~[na:na]
	at io.github.resilience4j.core.EventProcessor.processEvent(EventProcessor.java:57) ~[resilience4j-core-1.7.0.jar:1.7.0]
	at io.github.resilience4j.timelimiter.internal.TimeLimiterEventProcessor.consumeEvent(TimeLimiterEventProcessor.java:35) ~[resilience4j-timelimiter-1.7.0.jar:1.7.0]
	at io.github.resilience4j.timelimiter.internal.TimeLimiterImpl.publishEvent(TimeLimiterImpl.java:165) ~[resilience4j-timelimiter-1.7.0.jar:1.7.0]
	at io.github.resilience4j.timelimiter.internal.TimeLimiterImpl.onFailure(TimeLimiterImpl.java:160) ~[resilience4j-timelimiter-1.7.0.jar:1.7.0]
	at io.github.resilience4j.timelimiter.internal.TimeLimiterImpl.onError(TimeLimiterImpl.java:145) ~[resilience4j-timelimiter-1.7.0.jar:1.7.0]
	at io.github.resilience4j.kotlin.timelimiter.TimeLimiterKt.executeSuspendFunction(TimeLimiter.kt:55) ~[resilience4j-kotlin-1.7.0.jar:1.7.0]
	at io.github.resilience4j.kotlin.timelimiter.TimeLimiterKt$executeSuspendFunction$1.invokeSuspend(TimeLimiter.kt) ~[resilience4j-kotlin-1.7.0.jar:1.7.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.30.jar:1.5.30-release-413(1.5.30)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.5.30.jar:1.5.30-release-413(1.5.30)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	```

**Comment by RobWin** [comment]
Hi,
no idea how I could improve it :(
We are already using StampedLock.

**Comment by joost-de-vries** [comment]
Is it an idea to start a resilience4j blockhound integration? Like there is for Spring Reactor for example. https://github.com/reactor/reactor-core/blob/v3.3.0.RELEASE/reactor-core/src/main/java/reactor/core/scheduler/ReactorBlockHoundIntegration.java

**Comment by joost-de-vries** [comment]
That is: assuming that this is a false positive. And that call is indeed not blocking the underlying thread.

**Comment by joost-de-vries** [comment]
Like this
```kotlin
import reactor.blockhound.BlockHound
import reactor.blockhound.integration.BlockHoundIntegration

class Resilience4jBlockhoundIntegration : BlockHoundIntegration {

    override fun applyTo(builder: BlockHound.Builder) {
        builder.allowBlockingCallsInside("io.github.resilience4j.circularbuffer.ConcurrentEvictingQueue", "writeConcurrently")
    }
}
```

**Comment by MartijnMuijsers** [comment]
Why is `Thread.onSpinWait` considered to be blocking?

**Comment by rucko24** [comment]
> I'm not sure if it is a BlockHound bug but the call to `stampedLock.writeLock()` at `io.github.resilience4j.circularbuffer.ConcurrentEvictingQueue#writeConcurrently` is actually blocking.
> 
> As stated at the javadoc of `StampedLock`:
> 
> > /**
> > * Exclusively acquires the lock, blocking if necessary
> > * until available.
> > *
> > * @return a write stamp that can be used to unlock or convert mode
> > */

Hi Jordi, 

And in order not to complicate your life in this case, isn't it better to make a wrapper to this call and set the `Scheduler boundedElastic` and that's it? 

Personal taste, because if not I would have to add it to the 

`allowBlockingCallsInside`.
