### ISSUE TITLE
Circuitbreaker with CompletableFuture and fallback not working

### ISSUE THREAD

**Issue by himanshumps** [resilience4j/resilience4j#1574]
Resilience4j version: 1.7.0

Java version: 11

I have a method that returns completablefuture and I want to apply circuit breaker with fallback method.

```
circuitBreaker = CircuitBreaker.of("getCall", CircuitBreakerConfig.custom()
      .minimumNumberOfCalls(1)      //minimum number of call to be made in order to open the circuit
      .permittedNumberOfCallsInHalfOpenState(1)
      .enableAutomaticTransitionFromOpenToHalfOpen()
     // .ignoreExceptions(DocumentNotFoundException.class)
      .waitDurationInOpenState(Duration.ofSeconds(30))
      .build());
```

```
private CompletableFuture<GetResult> getDocumentById(AsyncBucket asyncBucket, String identifier) {
    return asyncBucket
      .defaultCollection()
      .get(identifier, GetOptions.getOptions().transcoder(RawJsonTranscoder.INSTANCE));
  }
```

```
Decorators
      .ofCompletionStage(() -> {
        log.info("Inside the primary method");
        return getDocumentById(paceAsyncBucket, identifier);
      })
      .withFallback(th -> {
        log.info("Inside the fallback method");
        return getDocumentById(fallbackAsyncBucket, identifier).join();
      })
      .withCircuitBreaker(circuitBreaker)
      .decorate()
      .get()
      .whenCompleteAsync((getResult, throwable) -> {
        if (throwable == null) {
          vertx.getOrCreateContext().runOnContext(v -> routingContext.response()
            .putHeader("content-type", "application/json")
            .end(getResult.contentAs(String.class)));
        } else {
          vertx.getOrCreateContext().runOnContext(v ->
            routingContext.response()
              .putHeader("content-type", "application/json")
              .end(convertStackTraceToString(throwable))
          );
        }
      });
```
The first call goes to fallback method but the second call gives the "io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'getCall' is OPEN and does not permit further calls"

Logs:

```
19:12:20.412 [vert.x-eventloop-thread-9] INFO  com.couchbase.test.vertx.couchbase.MainVerticle - Inside the primary method
19:12:20.832 [cb-io-kv-59-4] INFO  com.couchbase.test.vertx.couchbase.MainVerticle - Inside the fallback method
19:12:21.233 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - CircuitBreaker 'getCall' recorded an exception as failure:
com.couchbase.client.core.error.DocumentNotFoundException: Document with the given id not found {"completed":true,"coreId":"0x2abb5a480000001e","idempotent":true,"lastChannelId":"2ABB5A480000001E/0000000068127A5A","lastDispatchedFrom":"172.24.42.115:64435","lastDispatchedTo":"lpdospdbb50430.phx.tttt.com:11210","requestId":1154,"requestType":"GetRequest","retried":0,"service":{"bucket":"pace","collection":"_default","documentId":"222","opaque":"0xc2e","scope":"_default","type":"kv"},"status":"NOT_FOUND","timeoutMs":2500,"timings":{"dispatchMicros":396474,"totalDispatchMicros":396474,"totalServerMicros":0,"totalMicros":397063,"serverMicros":0}}
	at com.couchbase.client.core.error.DefaultErrorUtil.keyValueStatusToException(DefaultErrorUtil.java:45) ~[core-io-2.2.2.jar:?]
	at com.couchbase.client.java.kv.GetAccessor.lambda$get$0(GetAccessor.java:60) ~[java-client-3.2.2.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) [?:?]
	at com.couchbase.client.core.msg.BaseRequest.succeed(BaseRequest.java:154) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decodeAndComplete(KeyValueMessageHandler.java:384) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decode(KeyValueMessageHandler.java:363) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.channelRead(KeyValueMessageHandler.java:286) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.MemcacheProtocolVerificationHandler.channelRead(MemcacheProtocolVerificationHandler.java:85) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [core-io-2.2.2.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
19:12:21.233 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - CircuitBreaker 'getCall' recorded an exception as failure:
com.couchbase.client.core.error.DocumentNotFoundException: Document with the given id not found {"completed":true,"coreId":"0x2abb5a480000001e","idempotent":true,"lastChannelId":"2ABB5A480000001E/0000000068127A5A","lastDispatchedFrom":"172.24.42.115:64435","lastDispatchedTo":"lpdospdbb50430.phx.tttt.com:11210","requestId":1154,"requestType":"GetRequest","retried":0,"service":{"bucket":"pace","collection":"_default","documentId":"222","opaque":"0xc2e","scope":"_default","type":"kv"},"status":"NOT_FOUND","timeoutMs":2500,"timings":{"dispatchMicros":396474,"totalDispatchMicros":396474,"totalServerMicros":0,"totalMicros":397063,"serverMicros":0}}
	at com.couchbase.client.core.error.DefaultErrorUtil.keyValueStatusToException(DefaultErrorUtil.java:45) ~[core-io-2.2.2.jar:?]
	at com.couchbase.client.java.kv.GetAccessor.lambda$get$0(GetAccessor.java:60) ~[java-client-3.2.2.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) [?:?]
	at com.couchbase.client.core.msg.BaseRequest.succeed(BaseRequest.java:154) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decodeAndComplete(KeyValueMessageHandler.java:384) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.decode(KeyValueMessageHandler.java:363) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.KeyValueMessageHandler.channelRead(KeyValueMessageHandler.java:286) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.io.netty.kv.MemcacheProtocolVerificationHandler.channelRead(MemcacheProtocolVerificationHandler.java:85) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [core-io-2.2.2.jar:?]
	at com.couchbase.client.core.deps.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [core-io-2.2.2.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
19:12:21.246 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event ERROR not published
19:12:21.246 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event ERROR not published
19:12:21.247 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event FAILURE_RATE_EXCEEDED not published
19:12:21.247 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event FAILURE_RATE_EXCEEDED not published
19:12:21.252 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event STATE_TRANSITION not published
19:12:21.252 [cb-io-kv-59-4] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event STATE_TRANSITION not published
19:12:28.141 [vert.x-eventloop-thread-9] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event NOT_PERMITTED not published
19:12:28.141 [vert.x-eventloop-thread-9] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event NOT_PERMITTED not published
19:12:51.253 [CircuitBreakerAutoTransitionThread] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event STATE_TRANSITION not published
19:12:51.253 [CircuitBreakerAutoTransitionThread] DEBUG io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine - No Consumers: Event STATE_TRANSITION not published

```

**Comment by RobWin** [comment]
You have to change the order of your decorators. Think of it as an onion layer.

```
Decorators
      .ofCompletionStage(() -> {
        log.info("Inside the primary method");
        return getDocumentById(paceAsyncBucket, identifier);
      })
      .withCircuitBreaker(circuitBreaker)
      .withFallback(th -> {
        log.info("Inside the fallback method");
        return getDocumentById(fallbackAsyncBucket, identifier).join();
      })
```

**Comment by himanshu-gupta01** [comment]
Thanks

**Comment by RobWin** [comment]
If it works for you, please close the issue.

**Comment by himanshumps** [comment]
Working as intended. Thanks.
