### ISSUE TITLE
Resilience4j Micronaut error : Caused by: java.lang.ClassNotFoundException: io.github.resilience4j.consumer.EventConsumerRegistry

### ISSUE THREAD

**Issue by vinmorel** [resilience4j/resilience4j#1606]
resilience4j-micronaut: 1.7.1
resilience4j-ratelimiter: 1.7.1

Java version: 8
Micronaut: 2.4.0
kotlin: 1.4.32

I can't start my application when I add the micronaut-management package / micronaut-security package. 
Is there some sort of conflict with the resilience package?

Here's a demo of the problem : https://github.com/vinmorel/resilience4j-issue-micronaut

```
Message: Error loading bean [io.github.resilience4j.ratelimiter.RateLimiterRegistry]: io/github/resilience4j/consumer/EventConsumerRegistry
Path Taken: new ServiceReadyHealthIndicator$ApplicationEventListener$onServerStarted2$Intercepted(BeanContext $beanContext,Qualifier $qualifier,[List $interceptors])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.management.health.indicator.service.ServiceReadyHealthIndicator$ApplicationEventListener$onServerStarted2$Intercepted]

Message: Error loading bean [io.github.resilience4j.ratelimiter.RateLimiterRegistry]: io/github/resilience4j/consumer/EventConsumerRegistry
Path Taken: new ServiceReadyHealthIndicator$ApplicationEventListener$onServerStarted2$Intercepted(BeanContext $beanContext,Qualifier $qualifier,[List $interceptors])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1970)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:3091)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:2968)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:762)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1304)
	at io.micronaut.http.server.netty.NettyHttpServer.fireStartupEvents(NettyHttpServer.java:507)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:350)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:113)
	at io.micronaut.runtime.Micronaut.lambda$start$2(Micronaut.java:77)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at com.example.demo.ApplicationKt.main(Application.kt:8)
Caused by: io.micronaut.context.exceptions.BeanContextException: Error loading bean [io.github.resilience4j.ratelimiter.RateLimiterRegistry]: io/github/resilience4j/consumer/EventConsumerRegistry
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$36(DefaultBeanContext.java:1724)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1734)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:224)
	at io.micronaut.context.DefaultBeanContext.isCandidatePresent(DefaultBeanContext.java:3113)
	at io.micronaut.context.DefaultBeanContext.containsBean(DefaultBeanContext.java:719)
	at io.micronaut.context.BeanDefinitionRegistry.containsBean(BeanDefinitionRegistry.java:380)
	at io.micronaut.context.RequiresCondition.matchesPresenceOfBeans(RequiresCondition.java:560)
	at io.micronaut.context.RequiresCondition.processPostStartRequirements(RequiresCondition.java:211)
	at io.micronaut.context.RequiresCondition.matches(RequiresCondition.java:107)
	at io.micronaut.context.AbstractBeanContextConditional.isEnabled(AbstractBeanContextConditional.java:50)
	at io.micronaut.context.AbstractBeanDefinition.isEnabled(AbstractBeanDefinition.java:68)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$38(DefaultBeanContext.java:1733)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1734)
	at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:224)
	at io.micronaut.context.DefaultBeanContext.findBeanCandidatesInternal(DefaultBeanContext.java:2879)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:2947)
	at io.micronaut.context.AbstractBeanDefinition.lambda$doResolveBeanRegistrations$31(AbstractBeanDefinition.java:2157)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanRegistrationsWithGenericsFromArgument(AbstractBeanDefinition.java:2109)
	at io.micronaut.context.AbstractBeanDefinition.doResolveBeanRegistrations(AbstractBeanDefinition.java:2156)
	at io.micronaut.context.AbstractBeanDefinition.getBeanRegistrationsForConstructorArgument(AbstractBeanDefinition.java:1269)
	at io.micronaut.management.health.indicator.service.$ServiceReadyHealthIndicator$ApplicationEventListener$onServerStarted2$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1943)
	... 11 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/github/resilience4j/consumer/EventConsumerRegistry
	at io.github.resilience4j.micronaut.ratelimiter.$RateLimiterRegistryFactory$RateLimiterRegistry1Definition.<init>(Unknown Source)
	at io.github.resilience4j.micronaut.ratelimiter.$RateLimiterRegistryFactory$RateLimiterRegistry1DefinitionClass.load(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinitionReference.load(AbstractBeanDefinitionReference.java:62)
	at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$36(DefaultBeanContext.java:1722)
	... 49 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.github.resilience4j.consumer.EventConsumerRegistry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 53 common frames omitted

Process finished with exit code 1
```

**Comment by RobWin** [comment]
Hi,
unfortunately you need to add `io.github.resilience4j:resilience4j-consumer` to your classpath

**Comment by vinmorel** [comment]
Thanks. I added `implementation("io.github.resilience4j:resilience4j-consumer:1.7.1")` to my build.gradle and now it works
