### ISSUE TITLE
Using WebClient with Mono.zip stuck in half-open state.

### ISSUE THREAD

**Issue by murmur76** [resilience4j/resilience4j#1681]
Resilience4j version: 1.7.0

Java version: 11

Reproduce repo: https://github.com/murmur76/demo-resilience

```kotlin
package com.example.demo

import io.github.resilience4j.circuitbreaker.CircuitBreaker
import io.github.resilience4j.circuitbreaker.CircuitBreakerConfig
import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry
import io.github.resilience4j.reactor.circuitbreaker.operator.CircuitBreakerOperator
import mu.KotlinLogging
import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication
import org.springframework.web.reactive.function.client.WebClient
import reactor.core.publisher.Mono
import java.time.Duration

private val log = KotlinLogging.logger {}

@SpringBootApplication
class DemoApplication

fun main(args: Array<String>) {
	runApplication<DemoApplication>(*args)

	val circuit = CircuitBreaker.of("A", getDefaultConfig())
	circuit.getEventPublisher()
		.onStateTransition {
			log.info("CIRCUIT BREAKER " + it.getStateTransition().toString())
		}

	for (i in 1..50) {
		Mono.zip(
			request().transformDeferred(CircuitBreakerOperator.of(circuit)),
			request().transformDeferred(CircuitBreakerOperator.of(circuit)),
			request().transformDeferred(CircuitBreakerOperator.of(circuit))
		).onErrorResume { e ->
			log.error("error: $i", e)
			Mono.empty()
		}.block()
		Thread.sleep(1000)
	}
}

private fun request(): Mono<String> =
	WebClient.create("http://localhost:8080").get().retrieve().bodyToMono(String::class.java)

private fun getDefaultConfig(): CircuitBreakerConfig = CircuitBreakerConfig.custom()
	.automaticTransitionFromOpenToHalfOpenEnabled(true)
	.slidingWindow(10, 10, CircuitBreakerConfig.SlidingWindowType.COUNT_BASED)
	.failureRateThreshold(50F)
	.slowCallRateThreshold(100f)
	.slowCallDurationThreshold(Duration.ofSeconds(10))
	.waitDurationInOpenState(Duration.ofSeconds(5))
	.build()
```

When I use Mono.zip with mulitiple webclient call to no endpoint for error case, It stuck in half-open state and never get back to other state like below error log. I think it is related to `Mono.zip` method's cancellation behavior. If I do not use `Mono.zip` method it does not stuck in half-open state and get back to open state after max permitted calls.
Could you look into this issue?

```
io.github.resilience4j.circuitbreaker.CallNotPermittedException: CircuitBreaker 'A' is HALF_OPEN and does not permit further calls
	at io.github.resilience4j.circuitbreaker.CallNotPermittedException.createCallNotPermittedException(CallNotPermittedException.java:48) ~[resilience4j-circuitbreaker-1.7.0.jar:1.7.0]
	at io.github.resilience4j.reactor.circuitbreaker.operator.MonoCircuitBreaker.subscribe(MonoCircuitBreaker.java:40) ~[resilience4j-reactor-1.7.0.jar:1.7.0]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[reactor-core-3.4.15.jar:3.4.15]
	at reactor.core.publisher.Mono.block(Mono.java:1706) ~[reactor-core-3.4.15.jar:3.4.15]
	at com.example.demo.DemoApplicationKt.main(DemoApplication.kt:36) ~[main/:na]
```

**Comment by murmur76** [comment]
@RobWin 
Hi, Thanks for answer.
I've tried whether `Mono.zip` cancel other requests or not like below code.
```
	for (i in 1..50) {
		Mono.zip(
			request().transformDeferred(CircuitBreakerOperator.of(circuit))
				.doOnCancel { log.info("1 CANCELED") },
			request().transformDeferred(CircuitBreakerOperator.of(circuit))
				.doOnCancel { log.info("2 CANCELED") },
			request().transformDeferred(CircuitBreakerOperator.of(circuit))
				.doOnCancel { log.info("3 CANCELED") },
		).onErrorResume { e ->
			log.error("error: $i", e)
			Mono.empty()
		}.block()
		Thread.sleep(1000)
	}
```
and It seems cancellation works normal.
Also, If I add release permission logic like below code, circuit breaker does not stuck in half open state and works fine.
```
	for (i in 1..50) {
		Mono.zip(
			request().transformDeferred(CircuitBreakerOperator.of(circuit))
				.doOnCancel { log.info("1 CANCELED"); circuit.releasePermission() },
			request().transformDeferred(CircuitBreakerOperator.of(circuit))
				.doOnCancel { log.info("2 CANCELED"); circuit.releasePermission() },
			request().transformDeferred(CircuitBreakerOperator.of(circuit))
				.doOnCancel { log.info("3 CANCELED"); circuit.releasePermission() },
		).onErrorResume { e ->
			log.error("error: $i", e)
			Mono.empty()
		}.block()
		Thread.sleep(1000)
	}
```
Hope these tests bring you some clue.
Thank you.

**Comment by murmur76** [comment]
@RobWin 
Hi, is there any update?

**Comment by young0264** [comment]
@RobWin Hi, I’d like to work on this issue.

My initial approach is to first reproduce the behavior against the current master/latest version, then add a minimal regression test in the relevant module.

If the issue is still reproducible, I’d like to investigate the state transition / permission handling logic, especially around cancellation behavior with Mono.zip, and propose a fix based on that test.

Does this approach sound reasonable?
If so, could you assign this issue to me?
