### ISSUE TITLE
NoClassDefFoundError exception

### ISSUE THREAD

**Issue by Sotiris-Petroulakis** [resilience4j/resilience4j#1750]
Resilience4j version: 1.7.1

Java version: OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode) 

Hello, I'm getting a NoClassDefFoundError exception, when a method annotated with @RateLimiter(name = "fscan") is called. I am only using a single @RateLimiter(name = "fscan") , in one @Service method. 
To produce this problem, I send a request which contains 2 items. For each such item, the @RateLimiter annotated method is called once. When the request completes, I immediately re-send it (through Postman). Then that error occurs, and the SpringBoot app., is terminated. Sometimes, though, if I don't send the 2nd request immediately, the same error occurs after ~10 minutes of inactivity.

Please **note** that with Resilience4j version **1.7.0**, I haven't managed to reproduce this error!

application-properties:
```
resilience4j.ratelimiter:
  instances:
    fscan:
      limitForPeriod: 10
      limitRefreshPeriod: 25s
      timeoutDuration: 30s
      registerHealthIndicator: true
      eventConsumerBufferSize: 200

```
Relevant logs:
```
^[[30m2022-08-29 13:11:44,156^[[0;39m ^[[34mINFO ^[[0;39m [^[[34mSpringApplicationShutdownHook^[[0;39m] ^[[33morg.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup^[[0;39m: Failed to shut down 1 bean with phase value 2147483646 within timeout of 30000ms: [webServerStartStop]
^[[30m2022-08-29 13:11:44,158^[[0;39m ^[[39mDEBUG^[[0;39m [^[[34mSpringApplicationShutdownHook^[[0;39m] ^[[33morg.springframework.scheduling.concurrent.ExecutorConfigurationSupport^[[0;39m: Shutting down ExecutorService 'applicationTaskExecutor'
^[[30m2022-08-29 13:11:44,159^[[0;39m ^[[31mWARN ^[[0;39m [^[[34mSpringApplicationShutdownHook^[[0;39m] ^[[33morg.springframework.beans.factory.support.DisposableBeanAdapter^[[0;39m: Invocation of close method failed on bean with name 'threadPoolBulkheadRegistry'
java.lang.NoClassDefFoundError: io/vavr/collection/Array
        at io.github.resilience4j.bulkhead.internal.InMemoryThreadPoolBulkheadRegistry.getAllBulkheads(InMemoryThreadPoolBulkheadRegistry.java:151)
        at io.github.resilience4j.bulkhead.internal.InMemoryThreadPoolBulkheadRegistry.close(InMemoryThreadPoolBulkheadRegistry.java:229)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:239)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075)
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.doClose(ReactiveWebServerApplicationContext.java:149)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
		at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: io.vavr.collection.Array
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 16 common frames omitted
^[[30m2022-08-29 13:11:44,166^[[0;39m ^[[31mWARN ^[[0;39m [^[[34mSpringApplicationShutdownHook^[[0;39m] ^[[33morg.springframework.beans.factory.support.DisposableBeanAdapter^[[0;39m: Invocation of destroy method failed on bean with name 'reactorServerResourceFactory'
java.lang.NoClassDefFoundError: reactor/core/Exceptions
        at reactor.core.publisher.Operators.onOperatorError(Operators.java:719)
        at reactor.core.publisher.Operators.onOperatorError(Operators.java:697)
        at reactor.core.publisher.Operators.onOperatorError(Operators.java:679)
        at reactor.core.publisher.Operators.reportThrowInSubscribe(Operators.java:232)
        at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
        at reactor.core.publisher.Mono.block(Mono.java:1706)
        at org.springframework.http.client.reactive.ReactorResourceFactory.destroy(ReactorResourceFactory.java:224)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:213)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)

```
pom.xml:
```

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>gr.XXX</groupId>
    <artifactId>XXXservice</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>XxxService</name>
    <description>XxX submitted base64 files</description>
    <properties>
        <java.version>11</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

		<dependency>
		    <groupId>org.springframework.boot</groupId>
		    <artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>			

		<dependency>
		    <groupId>io.github.resilience4j</groupId>
		    <artifactId>resilience4j-spring-boot2</artifactId>
		    <version>1.7.1</version>
		</dependency>
		
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>


```

**Comment by RobWin** [comment]
Please see: https://github.com/resilience4j/resilience4j/issues/1472

I close it because it's a duplicate
