### ISSUE TITLE
TimeLimiter does NOT work in some calls when the CircuitBreaker is in HALF_OPEN state.

### ISSUE THREAD

**Issue by leventunver** [resilience4j/resilience4j#1804]
Resilience4j version: 1.7.1
 
Java version: 17
 
Hi,
 
We just noticed a behavior of resilience4j, and we are not sure if it is supposed to be that way. When the state of the circuit breaker goes from CLOSED to HALF_OPEN, there are times that the TimeLimiter does NOT work. And we understand that from our logs because the timeout exception is not `TimeoutException` or `TimeoutCancellationException` as we used to see. Is this an expected behavior?

Again, we are using the Kotlin implementation of the TimeLimiter [here.] (https://github.com/resilience4j/resilience4j/blob/master/resilience4j-kotlin/src/main/kotlin/io/github/resilience4j/kotlin/timelimiter/TimeLimiter.kt) 

Thanks in advance.

```
j.n.ConnectException: Connection timed out
	at sun.nio.ch.Net.connect0(Net.java)
	at sun.nio.ch.Net.connect(Net.java:579)
	at sun.nio.ch.Net.connect(Net.java:568)
	at s.n.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.net.Socket.connect(Socket.java:633)
	at java.net.Socket.connect(Socket.java:583)
	at s.net.NetworkClient.doConnect(NetworkClient.java:183)
	at s.n.w.h.HttpClient.openServer(HttpClient.java:498)
	at s.n.w.h.HttpClient.openServer(HttpClient.java:603)
	at s.n.w.p.h.HttpsClient.<init>(HttpsClient.java:266)
	at s.n.w.p.h.HttpsClient.New(HttpsClient.java:380)
	at s.n.w.p.h.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
	at s.n.w.p.h.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287)
	at s.n.w.p.h.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
	at s.n.w.p.h.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
	at s.n.w.p.h.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)
	at s.n.w.p.h.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)
	at s.n.w.p.h.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)
	at c.s.x.w.t.h.c.HttpClientTransport.getOutput(HttpClientTransport.java:91)
	... 131 common frames omitted
Wrapped by: c.s.x.w.c.ClientTransportException: HTTP transport error: java.net.ConnectException: Connection timed out
	at c.s.x.w.t.h.c.HttpClientTransport.getOutput(HttpClientTransport.java:104)
	at c.s.x.w.t.h.c.HttpTransportPipe.process(HttpTransportPipe.java:198)
	at c.s.x.w.t.h.c.HttpTransportPipe.processRequest(HttpTransportPipe.java:120)
	at c.s.x.w.t.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:80)
	at c.s.x.w.a.pipe.Fiber.__doRun(Fiber.java:1105)
	at c.s.x.w.a.pipe.Fiber._doRun(Fiber.java:1019)
	at c.s.x.w.a.pipe.Fiber.doRun(Fiber.java:988)
	at c.s.x.w.a.pipe.Fiber.runSync(Fiber.java:846)
	at c.s.x.ws.client.Stub.process(Stub.java:432)
	at c.s.x.w.c.s.SEIStub.doProcess(SEIStub.java:161)
	at c.s.x.w.c.s.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at c.s.x.w.c.s.SyncMethodHandler.invoke(SyncMethodHandler.java:61)
	at c.s.x.w.c.s.SEIStub.invoke(SEIStub.java:131)
	at jdk.proxy2.$Proxy215.loginService(Unknown Source)
	at k.c.i.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at k.c.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at i.g.r.k.t.TimeLimiterKt$executeSuspendFunction$2.invokeSuspend(TimeLimiter.kt:46)
	at i.g.r.k.t.TimeLimiterKt$executeSuspendFunction$2.invoke(TimeLimiter.kt)
	at k.c.i.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at k.c.TimeoutKt.setupTimeout(Timeout.kt:146)
	at k.c.TimeoutKt.withTimeout(Timeout.kt:44)
	at i.g.r.k.t.TimeLimiterKt.executeSuspendFunction(TimeLimiter.kt:45)
	at k.c.j.i.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at k.c.DispatchedTask.run(DispatchedTask.kt:106)
	at k.c.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at k.c.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at k.c.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at k.c.BuildersKt.runBlocking(Unknown Source:1)
	at k.c.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at k.c.BuildersKt.runBlocking$default(Unknown Source:1)
	at o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at o.s.a.a.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
	at i.g.r.b.Bulkhead.lambda$decorateCheckedSupplier$461fdbc9$1(Bulkhead.java:74)
	at i.g.r.b.Bulkhead.executeCheckedSupplier(Bulkhead.java:546)
	at i.g.r.b.c.BulkheadAspect.han...
```

**Comment by RobWin** [comment]
I can't see the CircuitBreaker in the stacktrace, but a Bulkhead? 
Usually the CircuitBreaker should throw an exception even before the Timelimiter is invoked.

**Comment by leventunver** [comment]
Here in the middle section. I will just separate that part so that it is more visible;

```
	at i.g.r.k.t.TimeLimiterKt$executeSuspendFunction$2.invokeSuspend(TimeLimiter.kt:46)
	at i.g.r.k.t.TimeLimiterKt$executeSuspendFunction$2.invoke(TimeLimiter.kt)
	at k.c.i.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
	at k.c.TimeoutKt.setupTimeout(Timeout.kt:146)
	at k.c.TimeoutKt.withTimeout(Timeout.kt:44)
	at i.g.r.k.t.TimeLimiterKt.executeSuspendFunction(TimeLimiter.kt:45)
```

Still on this line here: **(TimeLimiter.kt:46)**

https://github.com/resilience4j/resilience4j/blob/master/resilience4j-kotlin/src/main/kotlin/io/github/resilience4j/kotlin/timelimiter/TimeLimiter.kt#L46

**Comment by leventunver** [comment]
Any ideas @RobWin ?

**Comment by RobWin** [comment]
Usually we have an order like: circuitbreaker ( timelimiter ( function ) ).
Because you want to count TimeOutExceptions as errors.
Which means that if the CircuitBreaker is half_open, the timelimiter and function is not even invoked.
That's why I was asking where the CircuitBreaker is in your stacktrace.

**Comment by leventunver** [comment]
Ah, I see, sorry I completely misinterpreted your question. Is it possible that maybe this is one of those calls where the circuit breaker ALLOWED to pass through due to the state HALF_OPEN? So not all of them but some of them have to pass through, right?

As you mentioned, there is no CircuitBreaker here in the stacktrace and I don't know why. Another note; this is a Kotlin code (as you might have noticed already).

**Comment by RobWin** [comment]
The CircuitBreaker should have no affect on a TimeLimiter.
Can you see in your log that the NetworkClient also throws exceptions when the CircuitBreaker is closed?
Btw why do you use a TimeLimiter when the HTTP Client can do request timeouts for you?

**Comment by leventunver** [comment]
> Btw why do you use a TimeLimiter when the HTTP Client can do request timeouts for you?

I am not entirely sure why this path is chosen, but I think it might be due to the underlying client library that we have no control over. Also, the timeouts are being triggered in 2 mins which is quite a lot. But I will take your suggestion into consideration and propose it if possible.

> Can you see in your log that the NetworkClient also throws exceptions when the CircuitBreaker is closed?

I will check the logs and reply to you. But thanks for the help so far.

**Comment by leventunver** [comment]
I checked the logs and noticed that it is very rare to have the client connection timeouts when the CircuitBreaker is CLOSED. (Only 14 times out of ten thousands) When there are these client connection timeouts, it is almost always HALF_OPEN. However, when it is HALF_OPEN these client connection timeouts may or may not occur. The stacktrace seems identical so I won't post it here again.

**Comment by RobWin** [comment]
My only guess that it is related to how kotlin withTimeout implementation is working :(

**Comment by leventunver** [comment]
OK thank you so much for your input.
