### ISSUE TITLE
is resilience4j 1.7.0 compatible with vertx 4 (and java 8)?

### ISSUE THREAD

**Issue by maerean** [resilience4j/resilience4j#1874]
Resilience4j version: 1.7.0

Java version: 1.8.0_362

```xml
<vertx.version>4.3.5</vertx.version>
<netty.version>4.1.84.Final</netty.version>
```

All calls to VertxCircuitBreaker.executeFuture throw this exception when using vertx 4:

```java
java.lang.NoSuchMethodError: io.vertx.core.Future.future()Lio/vertx/core/Future;
	at io.github.resilience4j.circuitbreaker.VertxCircuitBreaker.lambda$decorateFuture$1(VertxCircuitBreaker.java:57) ~[resilience4j-vertx-1.7.0.jar:1.7.0]
	at io.github.resilience4j.circuitbreaker.VertxCircuitBreaker.executeFuture(VertxCircuitBreaker.java:43) ~[resilience4j-vertx-1.7.0.jar:1.7.0]
```

1. is resilience4j 1.7.0 compatible with vertx 4?
2. is resilience4j 1.7.0 compatible only with vertx 3?
3. is resilience4j 2.+ compatible with vertx 4?
4. what's the solution to use resilience4j with vertx 4 and java 8?

Resilience4j 2.+ uses Java 17 which is a breaking change for our project at this time.

**Comment by RobWin** [comment]
Hi, 
you actually know more than me.
Support for Vert.x was dropped a while ago, because not many from the community seemed to use Resilience4j together with Vert.x.
I don't even know the differences between Vert.x 3 and Vert.x 4 :(

**Comment by maerean** [comment]
In short, Vertx 4 is more asynchronous and you send a lot more callbacks to it than with Vertx 3.
