### ISSUE TITLE
Resilience - Add config values in the retryExceptionPredicate

### ISSUE THREAD

**Issue by LewandowskiAnthony** [resilience4j/resilience4j#1971]
Resilience4j version: 1.7.0

Java version: 19

Spring version : 2.7.5

Hello
In order to be more flexible with our application, we wanted to change this fixed status code declaration in predicate with values from our application.yaml retrieved with a configuration class but dependency injection and autowired field seems to not work with this solution.

Currently, we use this : 
<img width="891" alt="Capture d’écran 2023-06-05 à 10 24 17" src="https://github.com/resilience4j/resilience4j/assets/79880195/032f52b1-699d-4efe-9b67-ed06b78db4d3">

But we're aiming for this code : 
<img width="983" alt="image" src="https://github.com/resilience4j/resilience4j/assets/79880195/f26a71e8-4955-4717-ade6-45e5b7b94cc2">

But the dependency injection with AllArgs provoke this error : 
Caused by: io.github.resilience4j.core.InstantiationException: Unable to create instance of class: com.decathlon.orderdelivery.api.partner.config.resilience.RetryConditionalPredicate
	at io.github.resilience4j.core.ClassUtils.instantiatePredicateClass(ClassUtils.java:57)
	at io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties.buildRetryConfig(RetryConfigurationProperties.java:137)
	at io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties.createRetryConfig(RetryConfigurationProperties.java:97)
	at io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties.createRetryConfig(RetryConfigurationProperties.java:49)
	at io.github.resilience4j.retry.configure.RetryConfiguration.lambda$retryRegistry$0(RetryConfiguration.java:80)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at io.github.resilience4j.retry.configure.RetryConfiguration.retryRegistry(RetryConfiguration.java:78)
	at io.github.resilience4j.retry.autoconfigure.AbstractRetryConfigurationOnMissingBean.retryRegistry(AbstractRetryConfigurationOnMissingBean.java:76)
	at io.github.resilience4j.retry.autoconfigure.RetryConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$2ba95b25.CGLIB$retryRegistry$1(<generated>)
	at io.github.resilience4j.retry.autoconfigure.RetryConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$2ba95b25$$FastClassBySpringCGLIB$$19257b29.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at io.github.resilience4j.retry.autoconfigure.RetryConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$2ba95b25.retryRegistry(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 90 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.decathlon.orderdelivery.api.partner.config.resilience.RetryConditionalPredicate.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3641)
	at java.base/java.lang.Class.getConstructor(Class.java:2324)
	at io.github.resilience4j.core.ClassUtils.instantiatePredicateClass(ClassUtils.java:50)
	... 105 common frames omitted

Here's an exemple of our configuration bean : 
<img width="1326" alt="image" src="https://github.com/resilience4j/resilience4j/assets/79880195/ece0d0a1-affd-4e3d-8f4f-c11af834b07a">

And in our properties : 
<img width="913" alt="image" src="https://github.com/resilience4j/resilience4j/assets/79880195/dd01fada-fa0f-496d-a5d5-dec27a7f9f7d">

The properties are well set and the problem is only in our config bean retrievement

Also, autowired compile but set our config to null

Do you have any clue on how I can do that ?

Sincerely,

LEWANDOWSKI Anthony

**Comment by RobWin** [comment]
Hi,

can you share your config? I assume your configured `RetryConditionalPredicate.class` in our config file, or?
The problem is that Resilience4j is trying to use the default constructor to create an instance of the class. Resilience4j does not search for Spring Beans.

You can also change a RetryConfig programmatically:

```
@Bean
public RetryConfigCustomizer retryCustomizer(RetryConditionalPredicate exceptionPredicate) {
    return RetryConfigCustomizer
        .of("retryA", builder -> builder.retryOnException(exceptionPredicate));
}

```

**Comment by LewandowskiAnthony** [comment]
Hello Robwind ! 
Thanks a lot for this quick answer !
Here's my configuration : 
<img width="1016" alt="image" src="https://github.com/resilience4j/resilience4j/assets/79880195/7beebaa9-c355-40f8-baec-8935c4f62978">
Sorry, for the red predicate class, my IDE is quite capricious, but this predicate is well called 😄

**Comment by LewandowskiAnthony** [comment]
Hello,
Your solution worked perfectly !
I let the solution below if someone is interested.
Thanks a lot ! 
<img width="1136" alt="image" src="https://github.com/resilience4j/resilience4j/assets/79880195/14826316-7250-4204-b246-276a7d3cd31f">
