### ISSUE TITLE
when I use reset() the states do not change (always stays closed) and when I reboot my application in weblogic the states do not change (always stays closed)

### ISSUE THREAD

**Issue by husrevasici** [resilience4j/resilience4j#2034]
Hello,

I integrated the circuit breaker structure into my project. My project passes 10 million requests daily. But we have 2 problems.

The 1st problem is this -> I am using circuitBreaker.reset(); property. When there is a status other than Closed, the metrics are reset after calling the reset method. After that, even if it passes the failure rate, it does not switch from closed to open, so the status is broken.

Should I always pull the status to closed before calling the reset method and then reset it? Is there something wrong here?

2- My application is running on weblogic. When I stop start (reboot) my application on Weblogic, it does not switch from closed to open, the statuses are corrupted. What should I do for this?

note: I am using the version;

io.github.resilience4j
resilience4j-circuitbreaker
1.7.0

Java version: 8

Waiting for your feedback
Regards.

**Comment by RobWin** [comment]
Hi,

1) sounds like a bug. Could you create a test which reproduces it? I won't have time to do it.
2) Why should the circuitbreaker switch to open when you restart your application? Or did I missunderstand you?

**Comment by husrevasici** [comment]
Hello,
In case of stopping and starting the server in Weblogic, I run my circuitbreaeker object first, the transitionToClosedState() method, and then the reset() method. My goal is to reset the metrics in my circuit breaker object when stop start occurs.
After doing a stop start, when it reaches the threshold value, I get an error as shown in the stack trace below. Can you check ?

PROVIDER_CALLER_ERROR

Exception Occurred:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@14b33095 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@11e9da9b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
Stack Trace : 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@14b33095 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@11e9da9b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.<init>(CircuitBreakerStateMachine.java:660)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.lambda$transitionToOpenState$6(CircuitBreakerStateMachine.java:354)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.lambda$stateTransition$1(CircuitBreakerStateMachine.java:324)
	at java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:160)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.stateTransition(CircuitBreakerStateMachine.java:321)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.transitionToOpenState(CircuitBreakerStateMachine.java:353)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$ClosedState.checkIfThresholdsExceeded(CircuitBreakerStateMachine.java:618)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$ClosedState.onError(CircuitBreakerStateMachine.java:595)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.handleThrowable(CircuitBreakerStateMachine.java:233)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.onError(CircuitBreakerStateMachine.java:221)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateSupplier$4(CircuitBreaker.java:204)
	at io.github.resilience4j.core.SupplierUtils.lambda$recover$3(SupplierUtils.java:97)
	at io.github.resilience4j.decorators.Decorators$DecorateSupplier.get(Decorators.java:166)
	at com.thy.booking.circuitbreaker.aspect.BaseCircuitBreakerAspect.executeCircuitBreaker(BaseCircuitBreakerAspect.java:34)
	at com.thy.booking.circuitbreaker.aspect.DomesticFareProviderCircuitBreakerAspect.aroundDomesticFaresProviderCircuitBreaker(DomesticFareProviderCircuitBreakerAspect.java:38)
	at sun.reflect.GeneratedMethodAccessor1028.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.thy.circuitbreaker.CircuitBreakerProxy$$EnhancerBySpringCGLIB$$83798486.getAvailabilityFaresProxy(<generated>)
	at com.thy.alternative.orchestrator.availabilitymanagers.callmanager.AvailabilityCallManager.getFaresOfAvailability(AvailabilityCallManager.java:334)
	at com.thy.alternative.orchestrator.availabilitymanagers.callmanager.AvailabilityCallManager.getDomesticAvailability(AvailabilityCallManager.java:297)
	at com.thy.alternative.orchestrator.availabilitymanagers.callmanager.AvailabilityCallManager$$FastClassBySpringCGLIB$$1ae3e875.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.thy.alternative.orchestrator.availabilitymanagers.callmanager.AvailabilityCallManager$$EnhancerBySpringCGLIB$$69aa5794.getDomesticAvailability(<generated>)
	at com.thy.alternative.orchestrator.availabilitymanagers.callmanager.threadedstructure.AvailabilityCallable.call(AvailabilityCallable.java:48)
	at com.thy.alternative.orchestrator.availabilitymanagers.callmanager.threadedstructure.AvailabilityCallable.call(AvailabilityCallable.java:20)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by husrevasici** [comment]
Hello,
I have a another question.
I want to reset the metrics while in closed, open or halfopen states at runtime. For this .reset(); Will it be enough to run the method?
Can I run the reset() method while in different states?

**Comment by husrevasici** [comment]
Hi,
The bug I mentioned above has become increasingly important. It is a gentle reminder. Your feedback and guidance is very important for us.

**Comment by RobWin** [comment]
Seems the `java.util.concurrent.ScheduledThreadPoolExecutor@11e9da9b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 4]` has been terminated? 
I won't have time to look into it.
Could you check if `reset` is actually terminating the ScheduledThreadPoolExecutor, which is only used when `automaticTransitionFromOpenToHalfOpenEnabled -> true`

**Comment by husrevasici** [comment]
Hi Robert,
How do I know if the ScheduledThreadPoolExecutor terminates if automaticTransitionFromOpenToHalfOpenEnabled -> true ? 
Can you give me some guidance?

**Comment by RobWin** [comment]
I think you could just debug and see when and if the shutdown method of  ScheduledThreadPoolExecutor is executed.

**Comment by husrevasici** [comment]
Hi Robert,

1- thank you for your return. I will check it in detail and get back to you.
2- Also, We added the reset method to our project with the idea that the circuit breaker remains in OPEN status and there may be a disaster situation. Would you suggest another method?

Thanks.
Hüsrev.

**Comment by husrevasici** [comment]
Hi Robert,

I have an apim with a daily traffic of up to 20 million. We have integrated circuit breaker count based approach to this api. 

Suppose there is a scenario where the circuit breaker goes from CLOSED to OPEN. 
Due to the conf values we gave, we saw that we can use the refresh method of the circuit breaker if the application enters an infinite loop in the form of OPEN -> HALFOPEN -> OPEN -> HALFOPEN. 
What can we do here to get rid of the infinite loop other than running refresh?
I hope I was able to explain in the shortest way

Thanks.

**Comment by RobWin** [comment]
Why do you have this infinite loop?
This should only happen if the remote service is down. Then our application is expected to continuously check whether the service is available again.
Why do you need this config settings?

```
automaticTransitionFromOpenToHalfOpenEnabled -> true
waitIntervalFunctionInOpenState(IntervalFunction.of(Duration.ofSeconds(90))))
maxWaitDurationInHalfOpenState(Duration.ofSeconds(90))
```

When you disable `automaticTransitionFromOpenToHalfOpenEnabled`, the CircuitBreaker will remain OPEN until new requests are processed and the CircuitBreaker needs to check whether the remote service is operational again.

Why do you need a `maxWaitDuration` in HalfOpenState? 
This setting specifies the maximum duration the CircuitBreaker will remain in the HALF_OPEN state before transitioning back to the OPEN state if no successful requests are made during this time. It prevents the CircuitBreaker from staying in the HALF_OPEN state indefinitely. However, it's cautioned that setting this duration too low might cause the CircuitBreaker to transition back to the OPEN state prematurely, potentially impacting service availability. It's recommended to use a longer duration, such as 1 hour or more, depending on the expected recovery time of the remote service.


Try
```
```
automaticTransitionFromOpenToHalfOpenEnabled =  false
waitDurationInOpenState = Duration.ofSeconds(90)
```

**Comment by husrevasici** [comment]
Hello Robert

In our circuit breaker integration, we use it for timeout errors when we consume a different web service (we will soon add other errors we have defined). Circuit breaker ignores errors other than timeout returned from the web service we consume. For this reason, we used a structure that switches from OPEN to HALF_OPEN. As far as I understand from what you wrote, you said that there is no need to switch to half open if you are using it in down state. We want to use it for down and other errors. Do your same suggestions also apply in this case?

Thanks,
Hüsrev.

**Comment by RobWin** [comment]
Sorry, I didn't get your question:
> As far as I understand from what you wrote, you said that there is no need to switch to half open if you are using it in down state. We want to use it for down and other errors. Do your same suggestions also apply in this case?

If you have a system with a lot of traffic, then `automaticTransitionFromOpenToHalfOpenEnabled=true` is not needed.

**Comment by husrevasici** [comment]
Hı Robert,
Thank you for result. "automaticTransitionFromOpenToHalfOpenEnabled=false" when I made it false, I could not see any behavioral difference. What is the purpose of this parameter?

**Comment by RobWin** [comment]
Let's say the CB is open and the wait duration is 60s. Usually the CB will only switch to HalfOpen when a request is processed and 60s have expired. 
If you have a system without traffic it would stay open forever even after 60s.
If you don't want this, then you need a scheduled thread which transitions it to halfopen after 60s, even if no request is processed.

**Comment by RobWin** [comment]
No behavioral difference means you still get the exception?

**Comment by husrevasici** [comment]
Hi Robert,
there's no problem. Thank you for explaining in detail. 
I used .waitIntervalFunctionInOpenState(IntervalFunction.of(Duration.ofSeconds(60))) in circuit breaker design. 
I could not see the difference between **.waitIntervalFunctionInOpenState(IntervalFunction.of(Duration.ofSeconds(60)))** and **.waitDurationInOpenState(Duration.ofSeconds(60))** in your documentation. 
What is the difference between them?
Best regards.

**Comment by RobWin** [comment]
waitDurationInOpenState is a shortcut,
With the waitIntervalFunction you can have dynamic wait intervals

**Comment by husrevasici** [comment]
Hi Robert,
I turned off **.automaticTransitionFromOpenToHalfOpenEnabled(false)**. I tried the package as stop start (reboot) in Weblogic. Then I did tests. However, after switching from open to half open, I get the following error when switching to closed or halfopen and the application becomes inoperable

Caused by: java.lang.StackOverflowError
	at java.time.Instant.ofEpochMilli(Instant.java:346)
	at java.time.Clock$SystemClock.instant(Clock.java:471)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:677)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:681)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:681)

I saw that there was an issue opened for a similar bug. You have released a new version for this. But my application is not spring boot and we are using java 8. We are using circuitbreaker version 1.7.1. What should I do? Can you help me?

**Comment by husrevasici** [comment]
Hi Rebort,
**I did automaticTransitionFromOpenToHalfOpenEnabled -> false.**
I did the similar test again (I did the test after stop start (reboot) weblogic) and the Stack Trace changed. My test scenario is as follows.
CLOSED -> switched to OPEN and waited 60 seconds.
Switches to HALF_OPEN. After 10 requests, it decided to change state and while waiting for it to switch to OPEN again, I got the following error again.

Exception Occurred:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@40dc7f27 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@66a7a2ac[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
Stack Trace : 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@40dc7f27 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@66a7a2ac[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$HalfOpenState.<init>(CircuitBreakerStateMachine.java:1010)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.lambda$transitionToHalfOpenState$7(CircuitBreakerStateMachine.java:359)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.lambda$stateTransition$1(CircuitBreakerStateMachine.java:324)
	at java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:160)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.stateTransition(CircuitBreakerStateMachine.java:321)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.transitionToHalfOpenState(CircuitBreakerStateMachine.java:359)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.toHalfOpenState(CircuitBreakerStateMachine.java:752)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:678)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.acquirePermission(CircuitBreakerStateMachine.java:694)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.acquirePermission(CircuitBreakerStateMachine.java:206)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateSupplier$4(CircuitBreaker.java:194)
	at io.github.resilience4j.core.SupplierUtils.lambda$recover$3(SupplierUtils.java:97)
	at io.github.resilience4j.decorators.Decorators$DecorateSupplier.get(Decorators.java:166)
	at com.thy.booking.circuitbreaker.aspect.BaseCircuitBreakerAspect.executeCircuitBreaker(BaseCircuitBreakerAspect.java:34)
	at com.thy.booking.circuitbreaker.aspect.DomesticFareProviderCircuitBreakerAspect.aroundDomesticFaresProviderCircuitBreaker(DomesticFareProviderCircuitBreakerAspect.java:39)
	at sun.reflect.GeneratedMethodAccessor3222.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.thy.circuitbreaker.CircuitBreakerProxy$$EnhancerBySpringCGLIB$$d2b079be.getAvailabilityFaresProxy(<generated>)


note: I examined the ScheduledThreadPoolExecutor class as you said before, but I could not find a solution for the error received

**Comment by husrevasici** [comment]
++ Robert I forgot to add one part.
After I stop start weblogic, when I send a request again, it starts with CLOSED. Then it switches to CB OPEN according to my test scenario. It waits 60 seconds and when I send a request to switch to HALF_OPEN, it switches to HALF_OPEN. In HALF_OPEN, I want it to switch to OPEN again when I send 10 requests. When I wait for it to switch to OPEN when I send the 10th request, I get the error below. When I send the 11th request, I get the error as in the stak trace in the comment I wrote above.

Exception Occurred:
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@40dc7f27 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@66a7a2ac[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
Stack Trace : 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@40dc7f27 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@66a7a2ac[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$HalfOpenState.<init>(CircuitBreakerStateMachine.java:1010)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.lambda$transitionToHalfOpenState$7(CircuitBreakerStateMachine.java:359)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.lambda$stateTransition$1(CircuitBreakerStateMachine.java:324)
	at java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:160)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.stateTransition(CircuitBreakerStateMachine.java:321)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.transitionToHalfOpenState(CircuitBreakerStateMachine.java:359)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.toHalfOpenState(CircuitBreakerStateMachine.java:752)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:678)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.acquirePermission(CircuitBreakerStateMachine.java:694)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.acquirePermission(CircuitBreakerStateMachine.java:206)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateSupplier$4(CircuitBreaker.java:194)
	at io.github.resilience4j.core.SupplierUtils.lambda$recover$3(SupplierUtils.java:97)
	at io.github.resilience4j.decorators.Decorators$DecorateSupplier.get(Decorators.java:166)
	at com.thy.booking.circuitbreaker.aspect.BaseCircuitBreakerAspect.executeCircuitBreaker(BaseCircuitBreakerAspect.java:34)
	at com.thy.booking.circuitbreaker.aspect.DomesticFareProviderCircuitBreakerAspect.aroundDomesticFaresProviderCircuitBreaker(DomesticFareProviderCircuitBreakerAspect.java:39)
	at sun.reflect.GeneratedMethodAccessor3222.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.thy.circuitbreaker.CircuitBreakerProxy$$EnhancerBySpringCGLIB$$d2b079be.getAvailabilityFaresProxy(<generated>)


note: I examined the ScheduledThreadPoolExecutor class as you said before, but I could not find a solution for the error received

**Comment by RobWin** [comment]
The exception happens here https://github.com/resilience4j/resilience4j/blob/1.7/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L1006C13-L1011C14

I don't understand why the ScheduledThreadPoolExecutor is terminated.

As a fallback you could could set `maxWaitDurationInHalfOpenState=0` which is the default.

You could debug the following class: https://github.com/resilience4j/resilience4j/blob/1.7/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/SchedulerFactory.java

This is returning a newSingleThreadScheduledExecutor which is used to schedule the transition back to to open

**Comment by husrevasici** [comment]
Hi robert,
When I remove maxWaitDurationInHalfOpenState from the confs, the problem seems to be fixed when it takes the default value of 0. There does not seem to be a problem for now. I will continue my tests.
Thank you for your help. 
I have other questions in my head. Can I ask them too :)
Best regards.

**Comment by RobWin** [comment]
Sure, ask all your questions.
It just might take some time until I can answer

**Comment by husrevasici** [comment]
When should I use maxWaitDurationInHalfOpenState ?
Thanks.

**Comment by RobWin** [comment]
> ```
Why do you need `maxWaitDurationInHalfOpenState`:

This setting specifies the maximum duration the CircuitBreaker will remain in the HALF_OPEN state before transitioning back to the OPEN state if no successful requests are made during this time. It prevents the CircuitBreaker from staying in the HALF_OPEN state indefinitely. 

It's not really needed until you face an issue that the CircuitBreaker remains in HALF_OPEN, because of a bug in the implementation which is secured by the CircuitBreaker. Just test to set it to `0` and observe it. I usually don't use it in my systems.

**Comment by husrevasici** [comment]
Hi Robert,

I have some questions for you. 

1- My application works with count base. I want to use timebase, does it make sense? When should I use time based?
2- I have attached the confs I am currently using below. When I change slidingWindowType to Timebased, which confs should change and what should I pay attention to?


myConfig ->
failureRateThreshold -> 50%
slowCallRateThreshold(50.0F)
slowCallDurationThreshold(Duration.ofSeconds(10))
minimumNumberOfCalls -> 10
automaticTransitionFromOpenToHalfOpenEnabled -> false
waitIntervalFunctionInOpenState(IntervalFunction.of(Duration.ofSeconds(90))))
permittedNumberOfCallsInHalfOpenState -> 10
slidingWindowSize -> 10
slidingWindowType -> COUNT_BASED)

Thanks.

**Comment by husrevasici** [comment]
Hi Robert,
I look forward to your help when you are available.
Kind regards.

**Comment by RobWin** [comment]
Hi,
sry was on vacation.
The advantage of the time-based sliding window is that errors that occurred a long time ago may not be important anymore for the failure rate calculation anymore.
Usually if you have a system with a constant high request throughput it usually doesn't make a big difference.
But I would use time-based as a default.

**Comment by husrevasici** [comment]
Hi,
Thank you very much for your return Robert.
In the Time-based approach, it calculates according to the number of requests while in halfopen state. It only calculates time when it is in open state. For other states, it exhibits the same behavior as theCcount-based approach, right?
Thanks.

**Comment by RobWin** [comment]
The time-based sliding window is only used in the closed state.
The half-closed state is always count-based.
