### ISSUE TITLE
java.lang.StackOverflowError due to infinite loop in CircuitBreakerStateMachine$OpenState.tryAcquirePermission

### ISSUE THREAD

**Issue by polkosity** [resilience4j/resilience4j#2038]
Resilience4j version: 2.1.0

Java version: any

I've encountered java.lang.StackOverflowError due to infinite loop in CircuitBreakerStateMachine$OpenState.tryAcquirePermission in a production server, which was under strain.

After reviewing the code, I suggest it's caused by failure in the AtomicReference getAndUpdate call (CircuitBreakerStateMachine.java:333), as such failures can occurr due to contention among threads, according to Javadoc.  As an aside, Javadoc also states that the updateFunction should be side-effect free, which is not the case here.

Once the updateFunction fails during an attempted transition from open to half open state, the AtomicReference CircuitBreakerStateMachine.stateReference still refers to an OpenState whose AtomicBoolean OpenState.isOpen has already been set to false (CircuitBreakerStateMachine.java:812), so the transitionToHalfOpenState() call will not be attempted again, additionally retryAfterWaitDuration is already in the past for this OpenState object.  The effect is that OpenState.tryAcquirePermission calls itself recursively (CircuitBreakerStateMachine.java:737) until the StackOverflowError occurs.  

Please see the attached screenshot displaying a partial stack trace of the StackOverflowError, which was generated under resilience4j-circuitbreaker v1.7.1, but the relevant code sections have not changed since then. 

<img width="1011" alt="StackOverflowError" src="https://github.com/resilience4j/resilience4j/assets/6734401/9fd3fa9a-623a-48f6-ae9b-717f2b5ec2b6">

**Comment by RobWin** [comment]
Hi,
thank you for the analysis.
First time that I see this.  Do you have a proposal how to fix it?

**Comment by storozhukBM** [comment]
@polkosity 
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/atomic/AtomicReference.html#getAndUpdate(java.util.function.UnaryOperator) can't fail, it will be retried until update is successful.

I think the problem is here https://github.com/resilience4j/resilience4j/blob/12f66a31d7b4619ed0ffd1fddee9da683c41b9b7/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L812

where `compareAndSet` can return false to one thread before the other thread has finished `stateReference.getAndUpdate` execution. I think fix should remove `isOpen` boolean entirely and rely only on `stateReference`.

@RobWin what do you think?

**Comment by storozhukBM** [comment]
One more thing: if we decide to remove `isOpen` entirely, it can lead to high contention in `stateTransition` method, so to remedy this situation, we can rewrite it to use the CAS loop with checks if stateReference is not in the target state already before retries.

**Comment by fatso83** [comment]
Also being affected by this in a couple of systems. Not sure how we can help in supplying data.

**Comment by Hartigan** [comment]
I created [pull request](https://github.com/resilience4j/resilience4j/pull/2072) with fix. Also I removed unnecessary `synchronized`.

**Comment by Hartigan** [comment]
I found what we cannot remove `synchronized` because of [this code](https://github.com/resilience4j/resilience4j/blob/12f66a31d7b4619ed0ffd1fddee9da683c41b9b7/resilience4j-circuitbreaker/src/main/java/io/github/resilience4j/circuitbreaker/internal/CircuitBreakerStateMachine.java#L737). Pull request already updated

**Comment by RobWin** [comment]
@fatso83 do you really need to enable automaticTransitionFromOpenToHalfOpen? I assume we didn't find this issue earlier, because most people don't use it. You could disable it temporary until it is fixed.

**Comment by RobWin** [comment]
@Hartigan Thanks for you awesome analysis.

**Comment by fatso83** [comment]
Should not this be closed by #2072, now that it is merged?

> do you really need to enable automaticTransitionFromOpenToHalfOpen? I assume we didn't find this issue earlier, because most people don't use it

@RobWin We were discussing this at work and we don't really understand how/why you believe this. I am guessing this is down to some misunderstanding (on our part, most probably 😄). I _would think_ automatic handling is something most people would want? Otherwise one has to manually implement some kind of logic to close the circuit. Something seems off. Right now it seems like we need to listen for state transitions and create a Timer that asks to close the circuit x seconds into the future. This seems a bit simplistic. What are we missing here?

**Comment by RobWin** [comment]
@fatso83 
The flag `automaticTransitionFromOpenToHalfOpen` is really an optional feature which was added at a later point in time. 

The CircuitBreaker automatically switches from open to half-open when a new request is processed even without this flag. But it could mean that the state is OPEN until a new request arrives. Which confused some people who where just looking at Grafana boards in systems which didn't have much traffic.
Thus we introduces a thread which can automatically switch to HALF_OPEN after a period of time, even if no traffic is on the system.

But from the functional point of view there is no differences, except that it introduces problems right now :(

**Comment by fatso83** [comment]
Aha, thank you. That also explains why it was an issue by us, as we trigger alerts when the circuit breakers are open. So to have the circuit breaker alerts not be warning us all night we would need this. Makes sense, thanks!

**Comment by RobWin** [comment]
Well, If you have a production system which has not traffic at night, which would change the state automatically from open to half-open, why have warnings at night at all ;P

**Comment by RobWin** [comment]
Seems the issue not yet fixed. 
https://github.com/resilience4j/resilience4j/issues/2095

**Comment by bendb-instacart** [comment]
I just observed this myself in a unit test, using version 2.2.0:

```
java.lang.StackOverflowError
	at java.base/java.time.Instant.<init>(Instant.java:426)
	at java.base/java.time.Instant.create(Instant.java:416)
	at java.base/java.time.Instant.ofEpochSecond(Instant.java:334)
	at java.base/java.time.Clock.currentInstant(Clock.java:527)
	at java.base/java.time.Clock$SystemClock.instant(Clock.java:614)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:733)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:737)
```

Disabling `automaticTransitionFromOpenToHalfOpen` seems to avoid the issue.
