### ISSUE TITLE
(StackOverflowError) Endless loop while creating CircuitBreakerConfigurationProperties when using a custom base-config

### ISSUE THREAD

**Issue by doxic012** [resilience4j/resilience4j#2190]
Springboot version: 3.2.5
Spring Cloud Dependencies version: 3.1.0
Resilience4j version: 2.1.0 / 2.2.0 (upgraded manually to resilience4j-spring6:2.2.0)
Java version: 21.0.3 (temurin)

I found an issue on accident while trying to modify some of our configs.
We defined some named "base-configs" for our project to individually choose from:

```yml
# Count configuration with smaller sliding window
resilience4j.circuitbreaker.configs:
  countBasedSmall:
    slidingWindowType: count_based
    slidingWindowSize: 25
    failureRateThreshold: 50
    minimum-number-of-calls: 20
    permittedNumberOfCallsInHalfOpenState: 10

# Count configuration with larger sliding window
  countBasedLarge:
    slidingWindowType: count_based
    slidingWindowSize: 100
    failureRateThreshold: 50
    minimum-number-of-calls: 30
    permittedNumberOfCallsInHalfOpenState: 10

# Default configurations for time based circuit
  timeBased:
    slidingWindowType: time_based
    slidingWindowSize: 300
    failureRateThreshold: 50
    minimum-number-of-calls: 10
    permittedNumberOfCallsInHalfOpenState: 10
```

Now if we choose one of these configs by using the property `resilience4j.circuitbreaker.configs.default.base-config: countBasedSmall`, the application will never start due to a StackOverflowError, because the creation of the circuitbreaker configurations will recurse endlessly (see: https://github.com/resilience4j/resilience4j/blob/master/resilience4j-spring6/src/main/java/io/github/resilience4j/spring6/circuitbreaker/configure/CircuitBreakerConfiguration.java#L150)

I guess the problem resides at this line `else if (!instanceName.equals(DEFAULT) && configs.get(DEFAULT) != null)`, which will always be true, if we do not use the default config.
It will always check whether the DEFAULT config is != null though, which should be `configs.get(instanceName) != null` instead, because the default config is never null and will therefore always incorrectly run into the else if condition, triggering the same recursion step as the previous one, resulting in an endless loop.
(https://github.com/resilience4j/resilience4j/blob/master/resilience4j-framework-common/src/main/java/io/github/resilience4j/common/circuitbreaker/configuration/CommonCircuitBreakerConfigurationProperties.java#L65)

Stack:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'circuitBreakerRegistry' defined in class path resource [io/github/resilience4j/springboot3/circuitbreaker/autoconfigure/CircuitBreakerConfigurationOnMissingBean.class]: Failed to instantiate [io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry]: Factory method 'circuitBreakerRegistry' threw exception with message: null
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1335)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1165)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:254)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1443)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1353)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
	... 43 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry]: Factory method 'circuitBreakerRegistry' threw exception with message: null
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
	... 57 common frames omitted
Caused by: java.lang.StackOverflowError: null
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:576)
	at java.base/java.util.HashMap.get(HashMap.java:564)
	at io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties.createCircuitBreakerConfig(CommonCircuitBreakerConfigurationProperties.java:65)
	at io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties.createCircuitBreakerConfig(CommonCircuitBreakerConfigurationProperties.java:64)
	at io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties.createCircuitBreakerConfig(CommonCircuitBreakerConfigurationProperties.java:69)
	at io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties.createCircuitBreakerConfig(CommonCircuitBreakerConfigurationProperties.java:64)
	at io.github.resilience4j.common.circuitbreaker.configuration.CommonCircuitBreakerConfigurationProperties.createCircuitBreakerConfig(CommonCircuitBreakerConfigurationProperties.java:69)
...
```

If I remove  `resilience4j.circuitbreaker.configs.default.base-config: countBasedSmall` and just use the default config, it will start normally without any issue

**Comment by RobWin** [comment]
Urghs, thank you.
I almost can't believe it. I thought I have implemented some unit tests for this. 
Would you like to provide a PR to fix it?

**Comment by doxic012** [comment]
Sure, If I can find the time do properly fix it, I will try :)

**Comment by charb29** [comment]
Hi @doxic012 @RobWin, If you can't find the time to fix the issue I would love to help! i have free time between school and studies and would love to help out any way I can.

**Comment by RobWin** [comment]
Hello @charb29,
If you want to help and contribute, it would be awesome. I don't have much time at the moment. And the fix shouldn't be too complicated. A good way to start contributing to resilience4j

**Comment by RobWin** [comment]
Tests are here
https://github.com/resilience4j/resilience4j/blob/master/resilience4j-framework-common/src/test/java/io/github/resilience4j/common/circuitbreaker/configuration/CircuitBreakerConfigurationPropertiesTest.java

**Comment by charb29** [comment]
@RobWin Great, thank you! I'll start working on this weekend.

**Comment by charb29** [comment]
@RobWin Hi, is there a Discord or Slack channel where we can communicate with other developers?

**Comment by RobWin** [comment]
Yes, I can invite you to our slack channel if you give me some email address

**Comment by charb29** [comment]
@RobWin my email address is ocharb@mac.com

**Comment by charb29** [comment]
Hi @doxic012 and @RobWin,

I've been working on reproducing the issue you encountered. I created a minimal Spring Boot application with the same versions and circuit breaker registry properties as those used in your setup, but I haven't been able to reproduce the problem.

I might be missing something in my setup. Could you please provide more details on how you've configured the properties? Specifically, I'd like to understand the configuration that leads to the ```StackOverflowError```.

Thank you.

**Comment by doxic012** [comment]
Hi @charb29
I guess I can find some time on Thursday.
Can you create a small repo to work on your code, so I can take a look and maybe find the missing piece?

**Comment by charb29** [comment]
Hi @doxic012.

I've created the repository and added you as a contributor to it. Could you please review the setup and let me know if there are any missing pieces or issues we need to address? Your feedback will help us tackle this effectively.

Thanks!

**Comment by doxic012** [comment]
Hi @charb29.
I pushed a commit to reproduce the problem :)

Just download the sources for CommonCircuitBreakerConfigurationProperties.java and set a breakpoint at L65 or earlier. The endless recursion loop will happen in there.

**Comment by charb29** [comment]
Hi @doxic012 and @RobWin,

So it seems that the ```StackOverflowError``` is being caused due to the circular reference in the user defined configurations, which only exists in the default configuration. Specifically:

- The ```default``` configuration is referring to ```countBasedSmall``` using ```base-config: countBasedSmall```, creating a scenario where the ```createCircuitBreakerConfig``` recursively calls itself indefinitely. 

I am currently working on the fix.

**Comment by charb29** [comment]
Hi @doxic012 and @RobWin,

I've opened a [PR](https://github.com/resilience4j/resilience4j/pull/2199) with the fix. I've added you guys as reviewers as well.

**Comment by RobWin** [comment]
Thank you.

**Comment by charb29** [comment]
Hi @RobWin, could I be added to the Slack channel when ever possible? My email is ocharb@mac.com. Thank you

**Comment by doxic012** [comment]
@RobWin @charb29 
This issue can be closed right?

Can you tell me in which release (Spring-Cloud) this will be included?
