### ISSUE TITLE
Spring boot application fails to start after configuring resilient4j retry properties

### ISSUE THREAD

**Issue by victorherraiz** [resilience4j/resilience4j#2225]
Resilience4j version: 2.2.0
Java version: 17
Spring Boot: 3.3.4

Adding the following yaml to the configuration breaks the app start

```yaml
resilience4j:
  retry:
    configs:
      default:
        retry-exceptions:
          - java.lang.Throwable
    instances:
      bug:
        wait-duration: 200ms
```

The root exception is:
``` 
Caused by: java.lang.IllegalStateException: The intervalFunction was configured twice which could result in an undesired state. Please use either intervalFunction or intervalBiFunction.
	at io.github.resilience4j.retry.RetryConfig$Builder.build(RetryConfig.java:393) ~[resilience4j-retry-2.2.0.jar:2.2.0]
	at io.github.resilience4j.common.retry.configuration.CommonRetryConfigurationProperties.buildConfig(CommonRetryConfigurationProperties.java:166) ~[resilience4j-framework-common-2.2.0.jar:2.2.0]
	at io.github.resilience4j.common.retry.configuration.CommonRetryConfigurationProperties.createRetryConfig(CommonRetryConfigurationProperties.java:109) ~[resilience4j-framework-common-2.2.0.jar:2.2.0]
	at io.github.resilience4j.common.retry.configuration.CommonRetryConfigurationProperties.createRetryConfig(CommonRetryConfigurationProperties.java:50) ~[resilience4j-framework-common-2.2.0.jar:2.2.0]
	at io.github.resilience4j.spring6.retry.configure.RetryConfiguration.lambda$retryRegistry$0(RetryConfiguration.java:80) ~[resilience4j-spring6-2.2.0.jar:2.2.0]
	at java.base/java.util.HashMap.forEach(HashMap.java:1429) ~[na:na]
	at io.github.resilience4j.spring6.retry.configure.RetryConfiguration.retryRegistry(RetryConfiguration.java:78) ~[resilience4j-spring6-2.2.0.jar:2.2.0]
	at io.github.resilience4j.springboot3.retry.autoconfigure.AbstractRetryConfigurationOnMissingBean.retryRegistry(AbstractRetryConfigurationOnMissingBean.java:76) ~[resilience4j-spring-boot3-2.2.0.jar:2.2.0]
	at io.github.resilience4j.springboot3.retry.autoconfigure.RetryConfigurationOnMissingBean$$SpringCGLIB$$0.CGLIB$retryRegistry$5(<generated>) ~[resilience4j-spring-boot3-2.2.0.jar:2.2.0]
	at io.github.resilience4j.springboot3.retry.autoconfigure.RetryConfigurationOnMissingBean$$SpringCGLIB$$FastClass$$0.invoke(<generated>) ~[resilience4j-spring-boot3-2.2.0.jar:2.2.0]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.13.jar:6.1.13]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348) ~[spring-context-6.1.13.jar:6.1.13]
	at io.github.resilience4j.springboot3.retry.autoconfigure.RetryConfigurationOnMissingBean$$SpringCGLIB$$0.retryRegistry(<generated>) ~[resilience4j-spring-boot3-2.2.0.jar:2.2.0]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.13.jar:6.1.13]
	... 20 common frames omitted
```

It seems the inheritance of properties and default values is broken at some point.

**Comment by RobWin** [comment]
What happens if you do this

```
resilience4j:
  retry:
    configs:
      default:
        wait-duration: 100ms
        retry-exceptions:
          - java.lang.Throwable
    instances:
      bug:
        wait-duration: 200ms
```

**Comment by victorherraiz** [comment]
Starning the server with `wait-duration: xxx` in the default config do not throw any exception.
