### ISSUE TITLE
More than one circuit breaker for same backend results in "Operator called default onErrorDropped"

### ISSUE THREAD

**Issue by nischit7** [resilience4j/resilience4j#357]
First of all, this is not a straight forward issue.
It can occur under specific conditions.

I do have a business requirement where I have to define 2 circuit breakers config for the same downstream API. This back end is very unstable and a specific endpoint is error prone. Hence we are having 2 different circuit breaker level to abort further class.

From the below test case, we have a requirement where in for a collection of targets, we call this unstable API endpoint.

```
import java.time.Duration;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.reactivestreams.Publisher;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.github.resilience4j.circuitbreaker.CircuitBreaker;
import io.github.resilience4j.circuitbreaker.CircuitBreakerConfig;
import io.github.resilience4j.circuitbreaker.CircuitBreakerOpenException;
import io.github.resilience4j.circuitbreaker.CircuitBreakerRegistry;
import io.github.resilience4j.reactor.circuitbreaker.operator.CircuitBreakerOperator;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

public class CircuitBreakerSubscriberTest {

    private CircuitBreakerRegistry  circuitBreakerRegistry;

    @BeforeClass(alwaysRun = true)
    public void before() {
        this.circuitBreakerRegistry = CircuitBreakerRegistry.ofDefaults();
    }

   // With two circuit breakers
    @Test
    public void whenSubscriptionCancelled() {

        List<Integer> list = Arrays.asList(1);
        for (int index = 1; index < 10; index ++) {
            Flux.fromStream(list.stream())
                    .flatMap(integer -> Mono.just(integer)
                            .flatMap(emittedIndex -> {
                                return callOutboundApi();
                            })
                            .transform(decorateWithCircuitBreakerForSpecificEndpoint())
                            .map(str -> "Success.... sending good response")
                            .onErrorResume(NullPointerException.class, ex -> {
                                ex.printStackTrace();
                                return Mono.just("some error occured, sending error response " + ex);})
                            .onErrorResume(CircuitBreakerOpenException.class, ex -> {
                                ex.printStackTrace();
                                return Mono.just("some error occured, sending error response " + ex);})
                            .map(emittedObject -> {
                                // do some further business logic;
                                return "modified object, after applying further business logic";
                            }))
                    .reduce((s1, s2) -> s1)
                    .onErrorResume(RuntimeException.class, ex -> {
                        ex.printStackTrace();
                        return Mono.just("handled error response");
                    })
                    .block();
        }
    }

    // With one circuit breaker and a timeout
    @Test
    public void whenTimeoutIsAdded() {

        List<Integer> list = Arrays.asList(1);
        for (int index = 1; index < 10; index ++) {
            Flux.fromStream(list.stream())
                    .flatMap(integer -> Mono.just(integer)
                            .flatMap(emittedIndex -> {
                                return callOutboundApi();
                            })
                            .timeout(Duration.ofSeconds(5))
                            .transform(decorateWithCircuitBreakerForSpecificHost())
                            .map(str -> "Success.... sending good response")
                            .onErrorResume(NullPointerException.class, ex -> {
                                ex.printStackTrace();
                                return Mono.just("some error occured, sending error response " + ex);})
                            .onErrorResume(CircuitBreakerOpenException.class, ex -> {
                                ex.printStackTrace();
                                return Mono.just("some error occured, sending error response " + ex);})
                            .map(emittedObject -> {
                                // do some further business logic;
                                return "modified object, after applying further business logic";
                            }))
                    .reduce((s1, s2) -> s1)
                    .onErrorResume(RuntimeException.class, ex -> {
                        ex.printStackTrace();
                        return Mono.just("handled error response");
                    })
                    .block();
        }
    }

    private Mono<Integer> callOutboundApi() {
        // Lets assume the API is failing continuously
        return Mono.error(new NullPointerException("Server is down"));
    }

    protected <T> Function<Publisher<T>, Publisher<T>> decorateWithCircuitBreakerForSpecificEndpoint() {
        final CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
                .failureRateThreshold(100)
                .recordFailure(throwable -> throwable instanceof RuntimeException)
                .ringBufferSizeInClosedState(10)
                .ringBufferSizeInHalfOpenState(10)
                .waitDurationInOpenState(Duration.ofSeconds(5_000))
                .build();
        final CircuitBreaker circuitBreaker = this.circuitBreakerRegistry.circuitBreaker("test1", circuitBreakerConfig);
        return CircuitBreakerOperator.<T>of(circuitBreaker).andThen(decorateWithCircuitBreakerForSpecificHost());
    }

    protected <T> Function<Publisher<T>, Publisher<T>> decorateWithCircuitBreakerForSpecificHost() {
        final CircuitBreakerConfig circuitBreakerConfig = CircuitBreakerConfig.custom()
                .failureRateThreshold(10)
                .recordFailure(throwable -> throwable instanceof RuntimeException)
                .ringBufferSizeInClosedState(5)
                .ringBufferSizeInHalfOpenState(5)
                .waitDurationInOpenState(Duration.ofSeconds(5_000))
                .build();
        final CircuitBreaker circuitBreaker = this.circuitBreakerRegistry.circuitBreaker("test2", circuitBreakerConfig);
        return CircuitBreakerOperator.<T>of(circuitBreaker);
    }
}
```
When you run the above test, you will see the following output
```
java.lang.NullPointerException: Server is down
	at com.aw.dpa.wickedweed.circuitbreaker.CircuitBreakerSubscriberTest.callOutboundApi(CircuitBreakerSubscriberTest.java:63)
```
```
java.lang.NullPointerException: Server is down
	at com.aw.dpa.wickedweed.circuitbreaker.CircuitBreakerSubscriberTest.callOutboundApi(CircuitBreakerSubscriberTest.java:63)
```
```
java.lang.NullPointerException: Server is down
	at com.aw.dpa.wickedweed.circuitbreaker.CircuitBreakerSubscriberTest.callOutboundApi(CircuitBreakerSubscriberTest.java:63)
```
```
java.lang.NullPointerException: Server is down
	at com.aw.dpa.wickedweed.circuitbreaker.CircuitBreakerSubscriberTest.callOutboundApi(CircuitBreakerSubscriberTest.java:63)

java.lang.NullPointerException: Server is down
	at com.aw.dpa.wickedweed.circuitbreaker.CircuitBreakerSubscriberTest.callOutboundApi(CircuitBreakerSubscriberTest.java:63)
```
```
io.github.resilience4j.circuitbreaker.CircuitBreakerOpenException: CircuitBreaker 'test2' is open
	at io.github.resilience4j.reactor.circuitbreaker.operator.CircuitBreakerSubscriber.getThrowable(CircuitBreakerSubscriber.java:98)
```
```
00:30:24.394 [main] ERROR [o:, u:] reactor.core.publisher.Operators - Operator called default onErrorDropped
java.lang.NullPointerException: Server is down
	at com.aw.dpa.wickedweed.circuitbreaker.CircuitBreakerSubscriberTest.callOutboundApi(CircuitBreakerSubscriberTest.java:63)
```

Strangely, after circuit breaker 2 is OPEN, circuit breaker 1 subscriber is called and it results in dropped error exception.

In `ResilienceBaseSubscriber`,  I see the below condition and thats what causes the error dropped scenario.
```
Objects.requireNonNull(t, "onError");

        if (S.getAndSet(this, Operators.cancelledSubscription()) == Operators
                .cancelledSubscription()) {

            // already cancelled concurrently...
            if (permitted.get() == Permit.REJECTED) {
                // Ignore if the call was rejected
                return;
            }

            // signal on error dropped otherwise
            Operators.onErrorDropped(t, currentContext());
            return;
        }
```

In reality, this what I see -
1) on subscribe was called on subscriber1 (meant for circuit breaker 1).
2) subscriber1 initialized itself and called the actual subscriber. In this case, the actual subscriber is subscriber 2 (meant for circuit breaker 2).
3) It saw, its OPEN. Cancelled subscriber1 subscription and its also. 
4) The onError event occurred on subscriber1. It saw its subscription is cancelled and resulted in error dropped scenario.

Sometimes I think, there is nothing wrong with `ResilienceBaseSubscriber` current logic, but I am unable to use the way I wanted. Pls let me know of any suggestions

**Comment by RobWin** [comment]
Thanks for using Resilience4j. 
I hope I can have a look at your issue soon. There some other PRs which require my attention at the moment. please be patient with me ;)

**Comment by nischit7** [comment]
@RobWin ... any traction on this issue?

**Comment by RobWin** [comment]
No sorry, we are busy with other issues and enhancements at the moment. I hope I can have a look at it tomorrow or on Friday

**Comment by nischit7** [comment]
@RobWin ... any luck on this issue?

**Comment by RobWin** [comment]
Since you are using flatMapt it bight be related to this issue, which is actually an issue in Reactor itself:

https://github.com/resilience4j/resilience4j/issues/361

I try to debug it.

**Comment by RobWin** [comment]
Debugging this reactive chain is really challenging

**Comment by RobWin** [comment]
First finding:

`Mono.onError` terminates with the specified error immediately after being subscribed to. What you actually want to simulate is that your backend call is failing. You should actually use

```
return Mono.fromCallable(() -> {
            throw new NullPointerException("Server is down");
        });
```

**Comment by RobWin** [comment]
Yeah. I think I finally found the bug. That was a tough one.
Thank you for reporting it.

**Comment by RobWin** [comment]
Would you like to retest it when 0.15.0-SNAPSHOT is available?

**Comment by nischit7** [comment]
@RobWin .... first of all kudos to you for fixing it!!!
The day I reported this bug, I did try to find the cause and fix it myself. It got over my head and just gave up.
I will check the latest, validate and let you know
