### ISSUE TITLE
Resilience4j ratpack fails to run when dropwizard metrics in not on classpath

### ISSUE THREAD

**Issue by drmaas** [resilience4j/resilience4j#506]
The stacktrace isn't very helpful. It seems like MetricSet is being referenced even when metrics is disabled.

> Exception in thread "main" java.lang.NoClassDefFoundError: com/codahale/metrics/MetricSet
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2358)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:100)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:661)
	at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:51)
	at com.google.inject.internal.UntargettedBindingProcessor$1.visit(UntargettedBindingProcessor.java:35)
	at com.google.inject.internal.UntargettedBindingImpl.acceptTargetVisitor(UntargettedBindingImpl.java:42)
	at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:35)
	at com.google.inject.internal.UntargettedBindingProcessor.visit(UntargettedBindingProcessor.java:27)
	at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:93)
	at com.google.inject.internal.AbstractProcessor.process(AbstractProcessor.java:56)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:187)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at ratpack.guice.Guice.lambda$newInjectorFactory$2(Guice.java:209)
	at ratpack.guice.Guice.buildInjector(Guice.java:250)
	at ratpack.guice.Guice.registry(Guice.java:203)
	at ratpack.guice.Guice.lambda$registry$0(Guice.java:195)
	at ratpack.server.internal.DefaultRatpackServer$DefinitionBuild.lambda$new$0(DefaultRatpackServer.java:178)
	at ratpack.server.internal.ServerRegistry.buildUserRegistry(ServerRegistry.java:75)
	at ratpack.server.internal.ServerRegistry.serverRegistry(ServerRegistry.java:64)
	at ratpack.server.internal.DefaultRatpackServer.buildServerRegistry(DefaultRatpackServer.java:299)
	at ratpack.server.internal.DefaultRatpackServer.buildAdapter(DefaultRatpackServer.java:288)
	at ratpack.server.internal.DefaultRatpackServer$ReloadHandler.<init>(DefaultRatpackServer.java:419)
	at ratpack.server.internal.DefaultRatpackServer.buildHandler(DefaultRatpackServer.java:216)
	at ratpack.server.internal.DefaultRatpackServer.lambda$start$0(DefaultRatpackServer.java:127)
	at ratpack.exec.internal.ExecThreadBinding.bindFor(ExecThreadBinding.java:59)
	at ratpack.server.internal.DefaultRatpackServer.start(DefaultRatpackServer.java:127)
	at ratpack.server.RatpackServer.start(RatpackServer.java:93)
	at resilience4j.ratpack.App.main(App.java:12)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.MetricSet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 33 more

**Comment by drmaas** [comment]
App.java:

```
package resilience4j.ratpack;

import io.github.resilience4j.circuitbreaker.annotation.CircuitBreaker;
import io.github.resilience4j.ratpack.Resilience4jConfig;
import io.github.resilience4j.ratpack.Resilience4jModule;
import ratpack.guice.Guice;
import ratpack.server.RatpackServer;

public class App {

    public static void main(String[] args) throws Exception {
        RatpackServer.start(s -> s
                .serverConfig(c -> c
                        .development(true)
                        .yaml(App.class.getClassLoader().getResource("application.yml"))
                        .require("/resilience4j", Resilience4jConfig.class)
                )
                .registry(Guice.registry(b -> b
                        .module(Resilience4jModule.class)
//                        .module(DropwizardMetricsModule.class)
                        .bind(Something.class)
                ))
                .handlers(c -> c
                        .get("a", context -> {
                            Something something = context.get(Something.class);
                            context.render(something.a());
                        })
                        .get("b", context -> {
                            Something something = context.get(Something.class);
                            context.render(something.b());
                        })
                        .get("c", context -> {
                            Something something = context.get(Something.class);
                            context.render(something.c());
                        })
                    )
        );
    }

    public static class Something {

        @CircuitBreaker(name = "test1")
        public String a() {
            return "a";
        }

        @CircuitBreaker(name = "test1")
        public String b() throws DummyException1 {
            throw new DummyException1("b");
        }

        @CircuitBreaker(name = "test2")
        public String c() throws DummyException1 {
            throw new DummyException1("c");
        }

    }

    public static class DummyException1 extends Exception {
        DummyException1(String message) {
            super(message);
        }
    }

    public static class DummyException2 extends Exception {
        DummyException2(String message) {
            super(message);
        }
    }

}
```

**Comment by drmaas** [comment]
build.gradle:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.ratpack:ratpack-gradle:1.6.1"
    }
}

plugins {
    id 'com.github.johnrengelman.shadow' version '5.0.0'
    id 'java'
    id 'groovy'
}

apply plugin: "io.ratpack.ratpack-java"

repositories {
    mavenLocal()
    maven { url 'http://oss.jfrog.org/artifactory/oss-snapshot-local/' }
    jcenter()
}

dependencies {
    compile 'io.github.resilience4j:resilience4j-ratpack:0.17.0-SNAPSHOT'
//    compile 'io.github.resilience4j:resilience4j-metrics:0.17.0-SNAPSHOT'
    compile 'io.ratpack:ratpack-guice:1.6.1'
//    compile 'io.ratpack:ratpack-dropwizard-metrics:1.6.1'
    
    // Use the latest Groovy version for Spock testing
    testImplementation 'org.codehaus.groovy:groovy-all:2.5.6'

    // Use the awesome Spock testing and specification framework even with Java
    testImplementation 'org.spockframework:spock-core:1.2-groovy-2.5'
}

// Define the main class for the application
mainClassName = 'resilience4j.ratpack.App'
```

**Comment by drmaas** [comment]
I think there is an issue, where a new metric registry is auto-created. Ratpack has it's own already, which we should be able to pass in to e.g. `BulkheadMetrics.of(...)`.

**Comment by drmaas** [comment]
@RobWin I will take this one.

**Comment by drmaas** [comment]
Resolved in https://github.com/resilience4j/resilience4j/pull/507
