### ISSUE TITLE
How to use resilience4j-spring-boot correctly

### ISSUE THREAD

**Issue by MrRee1995** [resilience4j/resilience4j#557]
For some reason I have to use resilience4j with `spring boot 1.5.3.RELEASE`, but there seems to be no guide to spring boot 1.x in [**_User Guide_**](https://resilience4j.readme.io/docs), so I introduced the following dependencies according to the[ **_spring boot 2.x guide_**](https://resilience4j.readme.io/docs/getting-started-3):
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-aop</artifactId>
</dependency>
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-spring-boot</artifactId>
    <version>0.17.0</version>
</dependency>
```
I started my application and got the following error：
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bulkheadAspect' defined in class path resource [io/github/resilience4j/bulkhead/autoconfigure/BulkheadConfigurationOnMissingBean.class]: Unsatisfied dependency expressed through method 'bulkheadAspect' parameter 3; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<io.github.resilience4j.bulkhead.configure.BulkheadAspectExt>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=false)}
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.3.RELEASE.jar:1.5.3.RELEASE]
	at com.example.resilience4j_1_5_3.Resilience4j153Application.main(Resilience4j153Application.java:10) [classes/:na]
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<io.github.resilience4j.bulkhead.configure.BulkheadAspectExt>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=false)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1486) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1104) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741) ~[spring-beans-4.3.8.RELEASE.jar:4.3.8.RELEASE]
	... 19 common frames omitted
```
Then I found this code based on the error message:
```
@Bean
@ConditionalOnMissingBean
public BulkheadAspect bulkheadAspect(BulkheadConfigurationProperties bulkheadConfigurationProperties, 
        ThreadPoolBulkheadRegistry threadPoolBulkheadRegistry, 
        BulkheadRegistry bulkheadRegistry, 
        @Autowired(required = false) List<BulkheadAspectExt> bulkHeadAspectExtList,
        FallbackDecorators fallbackDecorators) {
	return bulkheadConfiguration.bulkheadAspect(bulkheadConfigurationProperties, threadPoolBulkheadRegistry, bulkheadRegistry, bulkHeadAspectExtList, fallbackDecorators);
}
```
The `List<BulkheadAspectExt> bulkHeadAspectExtList` parameter here doesn't seem to be necessary, is it because `@Autowired(required = false)` didn't take effect and I received this error?
What did i do wrong? Is there a guide to using `resilience4j-spring-boot` correctly?

**Comment by Romeh** [comment]
Hey @MrRee1995 ,

if you have to work with spring boot 1 anyhow , i would advise you to switch to version 1.5.22.RELEASE and that should works just fine with the proposed setup , please be informed we do test and update the code base based into last releases of spring boot 1 and 2 as much we could !

So are your forced to work with for spring boot 1.5.3.RELEASE or u can upgrade it to latest spring boot 1 release ?

**Comment by RobWin** [comment]
As a workaround you could add:

```
<dependency>
    <groupId>io.github.resilience4j</groupId>
    <artifactId>resilience4j-reactor</artifactId>
    <version>0.17.0</version>
</dependency>
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.2.8.RELEASE</version>
</dependency>
```

**Comment by MrRee1995** [comment]
> As a workaround you could add:
> 
> ```
> <dependency>
>     <groupId>io.github.resilience4j</groupId>
>     <artifactId>resilience4j-reactor</artifactId>
>     <version>0.17.0</version>
> </dependency>
> <dependency>
>     <groupId>io.projectreactor</groupId>
>     <artifactId>reactor-core</artifactId>
>     <version>3.2.8.RELEASE</version>
> </dependency>
> ```

It works, thanks

**Comment by MrRee1995** [comment]
> Hey @MrRee1995 ,
> 
> if you have to work with spring boot 1 anyhow , i would advise you to switch to version 1.5.22.RELEASE and that should works just fine with the proposed setup , please be informed we do test and update the code base based into last releases of spring boot 1 and 2 as much we could !
> 
> So are your forced to work with for spring boot 1.5.3.RELEASE or u can upgrade it to latest spring boot 1 release ?

I will temporarily use 1.5.3.RELEASE and then upgrade the version to springboot2 as soon as possible.Thanks
