### ISSUE TITLE
java.lang.IllegalStateException: Illegal state transition from CLOSED to HALF_OPEN

### ISSUE THREAD

**Issue by taer** [resilience4j/resilience4j#562]
In resilience4j-circuitbreaker version 0.16.0, we see this exception occasionally pop up. It's extremely rare.

The call is made like this: 
`circuitBreaker.executeCompletionStage(() -> connection.async().hvals(key));`

The setup of the breaker is 
```
        val timeoutCircuitBreaker = CircuitBreakerConfig.custom()
            .failureRateThreshold(25f)   //25 pecent of the last 100(ringBufferClosed) fail means open breaker
            .ringBufferSizeInClosedState(100)   // sample last 100 calls for failure reporting
            .waitDurationInOpenState(Duration.ofMillis(100))   // when tripped, sleep 100 ms before we try half open
            .ringBufferSizeInHalfOpenState(10)   // 10 requests go through in half open. They all need to pass to fully open
            .recordExceptions(RedisException::class.java)
            .build()

        val circuitBreaker = CircuitBreaker.of("redis-call", timeoutCircuitBreaker).apply {
            eventPublisher
                .onError { event -> Logger.info("redisCircuit: Error, {}", event) }
                .onIgnoredError { event -> Logger.info("redisCircuit: Ignored Exception, {}", event) }
                .onReset { event -> Logger.info("redisCircuit: Reset, {}", event) }
                .onStateTransition { event -> Logger.info("redisCircuit: State, {}", event) }
        }
```

```
java.lang.IllegalStateException: Illegal state transition from CLOSED to HALF_OPEN
	at io.github.resilience4j.circuitbreaker.CircuitBreaker$StateTransition.transitionBetween(CircuitBreaker.java:436)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.stateTransition(CircuitBreakerStateMachine.java:250)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.transitionToHalfOpenState(CircuitBreakerStateMachine.java:276)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:488)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.tryAcquirePermission(CircuitBreakerStateMachine.java:139)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateCompletionStage$1(CircuitBreaker.java:570)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.executeCompletionStage(CircuitBreaker.java:276)
```

The logs for those transitions as well as the error are: 
```
INFO  2019-08-13 13:02:55.661 [c.e.w.c.h.p.t.c.t.r.RedisCacheApiFactory] [f46ecad1d9b9] [a5ef4c168908b2ef] [lettuce-eventExecutorLoop-2-2] - redisCircuit: State, 2019-08-13T13:02:55.661654Z[Etc/UTC]: CircuitBreaker 'redis-call' changed state from CLOSED to OPEN
INFO  2019-08-13 13:02:55.762 [c.e.w.c.h.p.t.c.t.r.RedisCacheApiFactory] [452662468a81] [aff04930a6e9e899] [Proxy-Worker-0-Thread] - redisCircuit: State, 2019-08-13T13:02:55.762948Z[Etc/UTC]: CircuitBreaker 'redis-call' changed state from OPEN to HALF_OPEN
INFO  2019-08-13 13:02:55.775 [c.e.w.c.h.p.t.c.t.r.RedisCacheApiFactory] [d1d5681d64e6] [abd6fee720f9606c] [lettuce-epollEventLoop-4-6] - redisCircuit: State, 2019-08-13T13:02:55.774963Z[Etc/UTC]: CircuitBreaker 'redis-call' changed state from HALF_OPEN to CLOSED
ERROR 2019-08-13 13:02:55.787 [c.e.w.c.h.p.t.c.t.r.RedisCacheApi] [29c0dac3bea3] [b504939d89b2afc3] [Proxy-Worker-2-Thread] - FATAL: This should not be happening. Temporary catch to prevent 500
java.lang.IllegalStateException: Illegal state transition from CLOSED to HALF_OPEN
	at io.github.resilience4j.circuitbreaker.CircuitBreaker$StateTransition.transitionBetween(CircuitBreaker.java:436)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.stateTransition(CircuitBreakerStateMachine.java:250)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.transitionToHalfOpenState(CircuitBreakerStateMachine.java:276)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$OpenState.tryAcquirePermission(CircuitBreakerStateMachine.java:488)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.tryAcquirePermission(CircuitBreakerStateMachine.java:139)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateCompletionStage$1(CircuitBreaker.java:570)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.executeCompletionStage(CircuitBreaker.java:276)
INFO  2019-08-13 13:02:55.794 [c.e.w.c.h.p.t.c.t.r.RedisCacheApiFactory] [c30197c21830] [ad739a48a22d8274] [lettuce-epollEventLoop-4-6] - redisCircuit: State, 2019-08-13T13:02:55.794355Z[Etc/UTC]: CircuitBreaker 'redis-call' changed state from HALF_OPEN to CLOSED
INFO  2019-08-13 13:05:35.921 [c.e.w.c.h.p.t.c.t.r.RedisCacheApiFactory] [11145a98f8d1] [8919d08a8a97108e] [lettuce-eventExecutorLoop-2-3] - redisCircuit: State, 2019-08-13T13:05:35.921224Z[Etc/UTC]: CircuitBreaker 'redis-call' changed state from CLOSED to OPEN
INFO  2019-08-13 13:05:36.021 [c.e.w.c.h.p.t.c.t.r.RedisCacheApiFactory] [839d560ba10a] [adc69bf51414e364] [Proxy-Worker-0-Thread] - redisCircuit: State, 2019-08-13T13:05:36.021450Z[Etc/UTC]: CircuitBreaker 'redis-call' changed state from OPEN to HALF_OPEN
INFO  2019-08-13 13:05:36.026 [c.e.w.c.h.p.t.c.t.r.RedisCacheApiFactory] [4761fe18f6ff] [b82fafe15464d5ba] [lettuce-epollEventLoop-4-6] - redisCircuit: State, 2019-08-13T13:05:36.026803Z[Etc/UTC]: CircuitBreaker 'redis-call' changed state from HALF_OPEN to CLOSED
```

**Comment by RobWin** [comment]
Thanks, I check this tomorrow

**Comment by taer** [comment]
Just realized that I put the logs in the order splunk had them(reversed).   I just updated them in normal order

**Comment by RobWin** [comment]
I miss a state transition in your logs from CLOSED to OPEN, before the exception happens. Did you maybe miss/overlook it in splunk?

**Comment by taer** [comment]
That's all of it.  I see.
Closed -> open ->half_open -> closed -> half_open(the exception) -> closed -> open -> half_open -> closed

You did see my edit where I re-ordered it chronologically?

**Comment by RobWin** [comment]
I assume it was a race condition where two threads tried to transition from OPEN to HALF_OPEN at the same time.
Should be fixed with this commit -> https://github.com/resilience4j/resilience4j/pull/556/commits/3729f3bd773694465aed58a7b386d082ca4c0c52

**Comment by taer** [comment]
Awesome. Would it be possible to get this cut into a 17.0.1 release?
