### ISSUE TITLE
CircuitBreaker 'XX' tried an illegal state transition from OPEN to OPEN

### ISSUE THREAD

**Issue by wantedlzx** [resilience4j/resilience4j#646]
hi, team, I just write a benchmark with JMH, and find that when half-open transfer to open under multi threads, it will occur above exception. 

benchmark method is very easy:
```
if (circuitBreaker.tryAcquirePermission()) {
    circuitBreaker.onError(1, TimeUnit.SECONDS, timeoutException);
}
```

error stack:
```
io.github.resilience4j.circuitbreaker.IllegalStateTransitionException: CircuitBreaker 'XX' tried an illegal state transition from OPEN to OPEN
	at io.github.resilience4j.circuitbreaker.CircuitBreaker$StateTransition.transitionBetween(CircuitBreaker.java:476)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.lambda$stateTransition$1(CircuitBreakerStateMachine.java:242)
	at java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:160)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.stateTransition(CircuitBreakerStateMachine.java:241)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.transitionToOpenState(CircuitBreakerStateMachine.java:265)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$HalfOpenState.checkIfThresholdsExceeded(CircuitBreakerStateMachine.java:712)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine$HalfOpenState.onError(CircuitBreakerStateMachine.java:695)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.handleThrowable(CircuitBreakerStateMachine.java:174)
	at io.github.resilience4j.circuitbreaker.internal.CircuitBreakerStateMachine.onError(CircuitBreakerStateMachine.java:161)

```

before reference is half-open statemachine, but when execute stateTransition, reference already changed to open statemachine.

I'm sorry if not a problem :)

**Comment by RobWin** [comment]
Which version are you using?

**Comment by wantedlzx** [comment]
appreciate for your quick response 😃

My version is 1.0.0, is it out of date？

**Comment by RobWin** [comment]
No, but it's always important to know.
I similar issue shoud have been fixed in 1.0.0.
I just try to understand if it's a different issue now.

**Comment by wantedlzx** [comment]
I also found that issue, this issue seems can also use atomic object to avoid or maybe we can just add open to open tuple(will generate some useless event to busline).

**Comment by RobWin** [comment]
https://github.com/resilience4j/resilience4j/issues/562

**Comment by RobWin** [comment]
Yes, we can introduce a atomic flag. Would you like to do it?

**Comment by wantedlzx** [comment]
Sure, l’ll submit a pr. 😄
