### ISSUE TITLE
Resilience4j with sprinboot 2.2.0.Release

### ISSUE THREAD

**Issue by ozie03** [resilience4j/resilience4j#731]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version: 1.1.0

Java version: 11

Problem description:
on starting a springboot application version 2.2.0 with resilienc4j  spring boot starter, the application fails to startup with the following error : 

Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:398) ~[na:na]
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:277) ~[spring-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.util.ClassUtils.resolveClassName(ClassUtils.java:317) ~[spring-core-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	... 24 common frames omitted

**Comment by Romeh** [comment]
you need to add spring boot actuator dependency to ur project and it should be fine

**Comment by ozie03** [comment]
cool thanks

**Comment by duberton** [comment]
I do have the actuator as a dependency and i'm still having the same issue but i think it comes down to the fact that resilience4j (RateLimiter, Bulkhead and Retry autconfigurations) expects `EndpointAutoConfiguration` to be at the following package:

`org.springframework.boot.actuate.autoconfigure`

But, currently, spring-boot-actuator-autoconfigure-2.2.0.RELEASE.jar` has it located at: 

`org.springframework.boot.actuate.autoconfigure.endpoint`

**Comment by dlsrb6342** [comment]
@duberton 
In `CircuitBreakerAutoConfiguration`,
https://github.com/resilience4j/resilience4j/blob/2ea2540b4723f0dd4ac2ac0988ac9871ab95a185/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/circuitbreaker/autoconfigure/CircuitBreakerAutoConfiguration.java#L25

In `BulkheadAutoConfiguration`, 
https://github.com/resilience4j/resilience4j/blob/2ea2540b4723f0dd4ac2ac0988ac9871ab95a185/resilience4j-spring-boot2/src/main/java/io/github/resilience4j/bulkhead/autoconfigure/BulkheadAutoConfiguration.java#L26

Package paths are same as you mentioned. If you have any more question, Please make new issue and not use already closed issue.
