### ISSUE TITLE
NullPointerException when Service has static method

### ISSUE THREAD

**Issue by lucas-cunha** [resilience4j/resilience4j#732]
I'm trying to use ```resilience4j-feign``` on a Service that has a static method but it's throwing a NPE. Here is how my code was before using the library (only using Feign):

```
public interface OrderService {

    @Headers("Content-Type: application/json")
    @RequestLine("GET /orders")
    Orders getOrders();

    static OrderService connect(String url) {
        return Feign.builder()
            .encoder( new JacksonEncoder() )
            .decoder( new JacksonDecoder() )
            .target( OrderService.class, url );
    }
}
```
And I used to call it like this:
`Orders orders = OrderService.connect(url).getOrders();`

but, when using `resilience4j-feign` like this:
```
public interface OrderService {

    @Headers("Content-Type: application/json")
    @RequestLine("GET /orders")
    Orders getOrders();

    static OrderService connectWithRateLimiter(String url, RateLimiter rateLimiter) {
        FeignDecorators decorators = FeignDecorators.builder()
            .withRateLimiter( rateLimiter )
            .build();

        return Resilience4jFeign.builder( decorators )
            .encoder( new JacksonEncoder() )
            .decoder( new JacksonDecoder() )
            .target( OrderService.class, url );
    }
}
```

it throws error on line `.target( OrderService.class, url )`:
```
java.lang.NullPointerException: null
	at io.github.resilience4j.feign.DecoratorInvocationHandler.decorateMethodHandlers(DecoratorInvocationHandler.java:67) ~[resilience4j-feign-1.1.0.jar:1.1.0]
	at io.github.resilience4j.feign.DecoratorInvocationHandler.<init>(DecoratorInvocationHandler.java:45) ~[resilience4j-feign-1.1.0.jar:1.1.0]
	at io.github.resilience4j.feign.Resilience4jFeign$Builder.lambda$build$0(Resilience4jFeign.java:61) ~[resilience4j-feign-1.1.0.jar:1.1.0]
	at feign.ReflectiveFeign.newInstance(ReflectiveFeign.java:68) ~[feign-core-8.18.0.jar:8.18.0]
	at feign.Feign$Builder.target(Feign.java:198) ~[feign-core-8.18.0.jar:8.18.0]
	at feign.Feign$Builder.target(Feign.java:194) ~[feign-core-8.18.0.jar:8.18.0]
```

This problem doesn't happen if I use it the way it's shown on [Documentation](https://github.com/resilience4j/resilience4j/tree/master/resilience4j-feign) - **Decorating Feign Interfaces** - creating a `Service` with only the method to call an URL.

Resilience4j version:
1.1.0

Java version:
1.8.0_201

**Comment by hexmind** [comment]
Thank you for your detailed report. BTW it isn't typical Feign usage to put custom code into Feign interface ;)
I will check it.
