### ISSUE TITLE
Issue with Retry configuration - Spring-boot2

### ISSUE THREAD

**Issue by lyedla** [resilience4j/resilience4j#802]
Resilience4j version:
1.2.0

Java version:
8

Problem description:
When using a properties file to configure Retry, getting the below error.
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'retryEndpoint' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryAutoConfiguration$RetryAutoEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'retryEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryRegistry' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryConfigurationOnMissingBean.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.retry.RetryRegistry]: Factory method 'retryRegistry' threw exception; nested exception is java.lang.ClassCastException: java.util.HashMap cannot be cast to io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:235)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:226)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:101)
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:88)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:261)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:234)
	at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.callInitializers(ServletContextInitializerConfiguration.java:66)
	at org.springframework.boot.web.embedded.jetty.ServletContextInitializerConfiguration.configure(ServletContextInitializerConfiguration.java:55)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:517)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1454)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.security.SecurityHandler.doStart(SecurityHandler.java:361)
	at org.eclipse.jetty.security.ConstraintSecurityHandler.doStart(ConstraintSecurityHandler.java:449)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:415)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.springframework.boot.web.embedded.jetty.JettyWebServer.initialize(JettyWebServer.java:108)
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'retryEndpoint' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryAutoConfiguration$RetryAutoEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'retryEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryRegistry' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryConfigurationOnMissingBean.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.retry.RetryRegistry]: Factory method 'retryRegistry' threw exception; nested exception is java.lang.ClassCastException: java.util.HashMap cannot be cast to io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
	... 59 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'retryEndpoint' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryAutoConfiguration$RetryAutoEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'retryEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryRegistry' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryConfigurationOnMissingBean.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.retry.RetryRegistry]: Factory method 'retryRegistry' threw exception; nested exception is java.lang.ClassCastException: java.util.HashMap cannot be cast to io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1288)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083)
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.createEndpointBean(EndpointDiscoverer.java:149)
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.createEndpointBeans(EndpointDiscoverer.java:136)
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.discoverEndpoints(EndpointDiscoverer.java:125)
	at org.springframework.boot.actuate.endpoint.annotation.EndpointDiscoverer.getEndpoints(EndpointDiscoverer.java:119)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.servletEndpointRegistrar(ServletEndpointManagementContextConfiguration.java:76)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$836d7c2f.CGLIB$servletEndpointRegistrar$0(<generated>)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$836d7c2f$$FastClassBySpringCGLIB$$9ef3686c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363)
	at org.springframework.boot.actuate.autoconfigure.endpoint.web.ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration$$EnhancerBySpringCGLIB$$836d7c2f.servletEndpointRegistrar(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 60 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryRegistry' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryConfigurationOnMissingBean.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.retry.RetryRegistry]: Factory method 'retryRegistry' threw exception; nested exception is java.lang.ClassCastException: java.util.HashMap cannot be cast to io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties

**.conf file used -** 
resilience4j.retry : {
  configs: {
    default: {
      maxRetryAttempts: 5
      waitDuration: 100
      retryExceptions: ["ProcessingException.class, HttpHostConnectException.class"]
    }
  }
  instances: {
    instA: {
      waitDuration: 10s
      maxRetryAttempts: 2
      retryExceptionPredicate: {}
      resultPredicate: {}
      retryExceptions: ["ProcessingException.class", "HttpHostConnectException.class"]
    }
  }
}

**Comment by RobWin** [comment]
Hi, 
which version of Spring Boot are you using?
Why do you format your configuration in JSON?

**Comment by lyedla** [comment]
Hi @RobWin,
Spring boot version we are using is 2.1.2 .

**Comment by RobWin** [comment]
And why don't you use YAML? 
We never tested a JSON configuration. Does that even work? Seems that might be the issue: ```java.lang.ClassCastException: java.util.HashMap cannot be cast to io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties```

**Comment by RobWin** [comment]
Instances must be an Array of Objects instead of Object.

**Comment by lyedla** [comment]
Our project uses properties file.

**Comment by Romeh** [comment]
@lyedla  can you please share formatted version of your properties file so we can use it for reproducing the issue ?

**Comment by lyedla** [comment]
The project we are adding this to used proeprties file by default. 
Modifying the json to -resilience4j.retry : {
  configs: [
    {
      default: {
        maxRetryAttempts: 5
        waitDuration: 100
        retryExceptions: ["ProcessingException.class, HttpHostConnectException.class"]
      }
    }
  ]
  instances: [
    {
      instA: {
        waitDuration: 10s
        maxRetryAttempts: 2
        retryExceptionPredicate: {}
        resultPredicate: {}
        retryExceptions: ["ProcessingException.class", "HttpHostConnectException.class"]
      }
    }
  ]
}

Now i get new error -
	... 113 common frames omitted
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.util.HashMap<?, ?>] to type [java.util.Map<java.lang.String, io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties>] for value '{default={waitDuration=100, retryExceptions=[ProcessingException.class, HttpHostConnectException.class], maxRetryAttempts=5}}'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.util.HashMap<?, ?>] to type [io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:46)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191)
	at org.springframework.core.convert.support.CollectionToObjectConverter.convert(CollectionToObjectConverter.java:66)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:40)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191)
	at org.springframework.boot.context.properties.bind.BindConverter$CompositeConversionService.convert(BindConverter.java:177)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:98)
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:90)
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:65)
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:58)
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$2(Binder.java:304)
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:448)
	at org.springframework.boot.context.properties.bind.Binder$Context.access$100(Binder.java:388)
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:303)
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:261)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220)
	... 138 common frames omitted
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.util.HashMap<?, ?>] to type [io.github.resilience4j.common.retry.configuration.RetryConfigurationProperties$InstanceProperties]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194)
	at org.springframework.core.convert.support.MapToMapConverter.convertValue(MapToMapConverter.java:130)
	at org.springframework.core.convert.support.MapToMapConverter.convert(MapToMapConverter.java:85)
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:40)
	... 153 common frames omitted

**Comment by RobWin** [comment]
I don't get it.
What you are showing us is JSON-formatted and not a properties file.

**Comment by lyedla** [comment]
Sorry, we are using application.conf. which is json formatted

**Comment by RobWin** [comment]
Yes, as I said. This is the issue. The conversion from a configuration file to ConfigurationProperties classes is done by Spring Boot.
Spring Boot supports properties and yaml files. Spring Boot does not support JSON out-of-the-box. At least I'm not aware of it. Please see [External Configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config)
> Application properties packaged inside your jar (application.properties and YAML variants).

Please see https://github.com/spring-projects/spring-boot/issues/4027

**Comment by RobWin** [comment]
I think you are actually using [HOCON](https://github.com/lightbend/config/blob/master/HOCON.md#hocon-human-optimized-config-object-notation), or?

There is an error in this line or?
`retryExceptions: ["ProcessingException.class, HttpHostConnectException.class"]` should be
`retryExceptions: ["ProcessingException.class", "HttpHostConnectException.class"]`
