### ISSUE TITLE
spring-cloud2-resilience4j 1.3.0  java.lang.IllegalStateException: Not supported type by TimeLimiterAspect

### ISSUE THREAD

**Issue by zondahuman** [resilience4j/resilience4j#849]
Thanks for raising a Resilience4j issue.
Please provide a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

Resilience4j version:
```
<dependency>
       <groupId>io.github.resilience4j</groupId>
       <artifactId>resilience4j-spring-cloud2</artifactId>
       <version>1.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                </exclusion>
            </exclusions>
</dependency>
```

Java version:
JDK: 1.8
tomcat: 8

_

```
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-dependencies</artifactId>
<version>Hoxton.SR1</version>
<type>pom</type>
<scope>runtime</scope>
</dependency>
```

_

```
 <dependency>
                <!-- Import dependency management from Spring Boot -->
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.2.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
 </dependency>
```

```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
            <version>2.2.1.RELEASE</version>
        </dependency>
```

Problem description:
`

```
 @Override
    @CircuitBreaker(name = "findAll")
    @RateLimiter(name = "findAll")
    @TimeLimiter(name = "findAll")
    @Retry(name = "findAll")
    @Bulkhead(name = "findAll")
    public Map<String, Object> findAll(String params, String id) throws InterruptedException {
        Map<String, Object> resultMap = Maps.newHashMap();

        resultMap.put("params", params);
        resultMap.put("id", id);
        if (true) {
            Thread.sleep(10000L);
        }

        return resultMap;
    }

```

```
resilience4j.circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: false
        waitDurationInOpenState: 10s
        failureRateThreshold: 30
        eventConsumerBufferSize: 10
      queryById:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: false
        waitDurationInOpenState: 10s
        failureRateThreshold: 30
        eventConsumerBufferSize: 10
      findAll:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        slidingWindowType: TIME_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: false
        waitDurationInOpenState: 10s
        failureRateThreshold: 30
        eventConsumerBufferSize: 10
resilience4j.ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 50
        limitRefreshPeriod: 500
        timeoutDuration: 5
        eventConsumerBufferSize: 100
      queryById:
        registerHealthIndicator: false
        limitForPeriod: 5000
        limitRefreshPeriod: 500
        timeoutDuration: 5
        eventConsumerBufferSize: 1000
      findAll:
        registerHealthIndicator: false
        limitForPeriod: 5000
        limitRefreshPeriod: 500
        timeoutDuration: 5
        eventConsumerBufferSize: 1000
resilience4j.bulkhead:
    configs:
        default:
            maxConcurrentCall: 20
            maxWaitDuration: 10ms
        queryById:
            maxWaitDuration: 10ms
            maxConcurrentCall: 20
        findAll:
            maxWaitDuration: 10ms
            maxConcurrentCall: 20
resilience4j.thread-pool-bulkhead:
    configs:
      default:
        maxThreadPoolSize: 100
        coreThreadPoolSize: 20
        queueCapacity: 1000
      queryById:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1
      findAll:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1
resilience4j.retry:
    configs:
        default:
            maxRetryAttempts: 3
            waitDuration: 2000
        queryById:
            maxRetryAttempts: 3
            waitDuration: 2000
        findAll:
            maxRetryAttempts: 3
            waitDuration: 2000


resilience4j.timelimiter:
    configs:
        default:
            timeoutDuration: 2s
            cancelRunningFuture: true
        queryById:
            timeoutDuration: 1s
            cancelRunningFuture: true
        findAll:
            timeoutDuration: 1s
            cancelRunningFuture: true
```

```
[2020-02-06 23:34:01] [ERROR] [com.abin.lee.spring.boot.resilience.controller.ResiliencePurposeController:69] -- queryById--params=lee,e=java.lang.IllegalStateException: Not supported type by TimeLimiterAspect
	at io.github.resilience4j.timelimiter.configure.TimeLimiterAspect.proceed(TimeLimiterAspect.java:112)
	at io.github.resilience4j.timelimiter.configure.TimeLimiterAspect.timeLimiterAroundAdvice(TimeLimiterAspect.java:91)
	at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$3f69f149$1(Retry.java:137)
	at io.github.resilience4j.retry.Retry.executeCheckedSupplier(Retry.java:419)
	at io.github.resilience4j.retry.configure.RetryAspect.handleDefaultJoinPoint(RetryAspect.java:181)
	at io.github.resilience4j.retry.configure.RetryAspect.proceed(RetryAspect.java:138)
	at io.github.resilience4j.retry.configure.RetryAspect.retryAroundAdvice(RetryAspect.java:117)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at com.abin.lee.spring.boot.resilience.service.impl.ResiliencePurposeServiceImpl$$EnhancerBySpringCGLIB$$d38b8e9.queryById(<generated>)
	at com.abin.lee.spring.boot.resilience.controller.ResiliencePurposeController.queryById(ResiliencePurposeController.java:67)
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:108)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)



```
`

what is this? @RobWin

**Comment by dlsrb6342** [comment]
Hi @zondahuman 
TimeLimiterAspect only support reactive type(rxjava or reactor) or `CompletionStage` .
https://github.com/resilience4j/resilience4j/blob/93c69014dbd9a05d4c032e0e204beef735ef1c76/resilience4j-spring/src/main/java/io/github/resilience4j/timelimiter/configure/TimeLimiterAspect.java#L100-L116

**Comment by zondahuman** [comment]
> Hi @zondahuman
> TimeLimiterAspect only support reactive type(rxjava or reactor) or `CompletionStage` .
> https://github.com/resilience4j/resilience4j/blob/93c69014dbd9a05d4c032e0e204beef735ef1c76/resilience4j-spring/src/main/java/io/github/resilience4j/timelimiter/configure/TimeLimiterAspect.java#L100-L116

How to configure to support? @dlsrb6342

**Comment by dlsrb6342** [comment]
If you want to check method execution time, you have to use reactive type or `CompletableFuture` as a return type. Please change method's return type.

**Comment by zondahuman** [comment]
> If you want to check method execution time, you have to use reactive type or `CompletableFuture` as a return type. Please change method's return type.

i seem to ubderstand, thx @dlsrb6342
