### ISSUE TITLE
rxjava: Circuit Not opening

### ISSUE THREAD

**Issue by himanshumps** [resilience4j/resilience4j#861]
Resilience4j version: 1.3.1

Java version: 1.8

I am trying to open circuit in case of exception and wait for specified amount to time before making it half open.

Code:

CircuitBreaker config
```
CircuitBreaker createCircuitBreaker(String name) {
        return CircuitBreaker.of(name, CircuitBreakerConfig.custom()
                .permittedNumberOfCallsInHalfOpenState(1)
                .enableAutomaticTransitionFromOpenToHalfOpen()
                .ignoreExceptions(NoSuchElementException.class)
                .recordExceptions(TimeoutException.class, CouchbaseException.class, CircuitBreakerOpenException.class)
                .waitDurationInOpenState(Duration.ofSeconds(60))
                .build());
    }
```

Reactive Code:

Declarations:
```
private final CircuitBreaker circuitBreakerForCouchbaseReadKey;

private final CircuitBreakerOperator<RawJsonDocument> circuitBreakerOperatorForKeyForRawDocument;

circuitBreakerForCouchbaseReadKey = config.createCircuitBreaker("circuitBreakerForCouchbaseReadKey");

circuitBreakerOperatorForKeyForRawDocument = CircuitBreakerOperator.of(circuitBreakerForCouchbaseReadKey);
```

Code:
```
getRawJsonDocumentFromBucketWithCircuit(key, primaryAsyncBucket, traceId)
                .compose(circuitBreakerOperatorForKeyForRawDocument)
                .onErrorResumeNext(e -> {
                    // Primary main bucket exception, Get from secondary main bucket
                    log.info(new LogEvent("getRawJsonDocument - Secondary bucket", traceId)
                            .addEntry("key", key).addThrowable(e).toString());
                    return getRawJsonDocumentFromBucket(key, secondaryAsyncBucket, traceId);
                })
                .observeOn(Schedulers.io());

private Flowable<RawJsonDocument> getRawJsonDocumentFromBucketWithCircuit(String key, AsyncBucket bucket, String traceId) {
        if (circuitBreakerForCouchbaseReadKey.tryAcquirePermission()) {
            return getRawJsonDocumentFromBucket(key, bucket, traceId);
        } else {
            return Flowable.error(new CircuitBreakerOpenException("Circuit is OPEN"));
        }
    }
```

**Comment by RobWin** [comment]
Do you use Spring Boot 2?

You don't have to call `tryAcquirePermission` or any other method by yourself. The CircuitBreakerOperator is handling everythig for you.

What exactly does not work?

**Comment by himanshumps** [comment]
I am using rxjava 2 not spring reactor

**Comment by RobWin** [comment]
The same applies to RxJava2. But ofcourse of have to adapt the executeWithFallback method.

**Comment by himanshumps** [comment]
There is no transform in rxjava2. Should I use compose in place of that ?

In your case, will the first method not be called even in case of circuit being open ?

**Comment by RobWin** [comment]
Yes, please use compose instead.
No, the CircuitBreakerOperator protects it.

**Comment by himanshumps** [comment]
Do I still need transform(TimeLimiterOperator.of(timeLimiter))

**Comment by RobWin** [comment]
No, but it is usefull to restrict the time of your method.

**Comment by himanshumps** [comment]
Will give it a try from a test and will share results

**Comment by himanshumps** [comment]
Will it be possible to share the rxjava equivalent of the code. I am having trouble getting it done .. This is what I have come so far with (Compilation issues)

```
import com.test.pace.pace_common_module.exception.CircuitBreakerOpenException;
import com.couchbase.client.core.CouchbaseException;
import io.github.resilience4j.circuitbreaker.CallNotPermittedException;
import io.github.resilience4j.circuitbreaker.CircuitBreaker;
import io.github.resilience4j.circuitbreaker.CircuitBreakerConfig;
import io.github.resilience4j.circuitbreaker.operator.CircuitBreakerOperator;
import io.reactivex.Flowable;
import io.reactivex.FlowableSubscriber;
import io.reactivex.functions.Function;
import org.reactivestreams.Subscription;

import java.sql.Time;
import java.time.Duration;
import java.util.NoSuchElementException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeoutException;

public class TestCircuit {
    CircuitBreaker circuitBreaker = createCircuitBreaker("circuitBreaker");
    CircuitBreakerOperator<Object> circuitBreakerOperator = CircuitBreakerOperator.of(circuitBreaker);

    public static void main(String[] args) {
        TestCircuit testCircuit = new TestCircuit();
        testCircuit.testCircuit();
    }
    private void testCircuit() {

        Object[] arr = new Object[]{"a", new TimeoutException(), "b", "c", new TimeoutException(), "d", "e"};
        for(Object o : arr) {
           executeWithFallback(() -> mainMethod(o), (e) -> fallbackMethod(o));
        }
    }
    private <T> Flowable<T> executeWithFallback(Flowable<T> publisher, Function<Throwable,Flowable<T>> fallback){
        return publisher
                .compose(CircuitBreakerOperator.of(circuitBreaker))
                .onErrorResumeNext(fallback);

    }
    private Flowable<Object> mainMethod(Object o) {
            System.out.println("Inside method1");
            return Flowable.just(o);
    }

    private Flowable<Object> fallbackMethod(Object o) {
        System.out.println("Inside method2");
        return Flowable.just(new String("method2 - pass"));
    }

    CircuitBreaker createCircuitBreaker(String name) {
        return CircuitBreaker.of(name, CircuitBreakerConfig.custom()
                .permittedNumberOfCallsInHalfOpenState(1)
                .enableAutomaticTransitionFromOpenToHalfOpen()
                .ignoreExceptions(NoSuchElementException.class)
                .recordExceptions(TimeoutException.class, CouchbaseException.class, CircuitBreakerOpenException.class)
                .waitDurationInOpenState(Duration.ofSeconds(60))
                .build());
    }
}
```

**Comment by RobWin** [comment]
You should read a little bit more documentation about RxJava2, if you want to use it.
You should read this -> https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#testing
Your code has no subscriber.

**Comment by RobWin** [comment]
Try this:

```
public class TestCircuit {

    CircuitBreaker circuitBreaker;

    @Before
    public void setUp() {
        circuitBreaker = CircuitBreaker.of("circuitBreaker", CircuitBreakerConfig.custom()
            .permittedNumberOfCallsInHalfOpenState(1)
            .enableAutomaticTransitionFromOpenToHalfOpen()
            .ignoreExceptions(NoSuchElementException.class)
            .recordExceptions(TimeoutException.class)
            .waitDurationInOpenState(Duration.ofSeconds(60))
            .build());
    }

    @Test
    private void testCircuit() {
        executeWithFallback(Flowable.just("a"), (e) -> Flowable.just("b"))
            .test()
            .assertValue("a");
    }

    @Test
    private void testException() {
        executeWithFallback(Flowable.error(new TimeoutException()), (e) -> Flowable.just("b"))
            .test()
            .assertValue("b");
    }

    @Test
    private void testOpenCircuitBreaker() {
        circuitBreaker.transitionToOpenState();
        executeWithFallback(Flowable.just("a"), (e) -> Flowable.just("b"))
            .test()
            .assertValue("b");
    }

    private <T> Flowable<T> executeWithFallback(Flowable<T> publisher,
        Function<Throwable, Flowable<T>> fallback) {
        return publisher
            .compose(CircuitBreakerOperator.of(circuitBreaker))
            .onErrorResumeNext(fallback);
    }
}
```

**Comment by himanshumps** [comment]
Hi,

It is not working as intended. The circuit should remain for 60 seconds but that is not happening. The circuit is not opening even after throwing the recorded exception.

```
import com.test.pace.pace_common_module.exception.CircuitBreakerOpenException;
import com.couchbase.client.core.CouchbaseException;
import io.github.resilience4j.circuitbreaker.CallNotPermittedException;
import io.github.resilience4j.circuitbreaker.CircuitBreaker;
import io.github.resilience4j.circuitbreaker.CircuitBreakerConfig;
import io.github.resilience4j.circuitbreaker.operator.CircuitBreakerOperator;
import io.reactivex.Flowable;
import io.reactivex.functions.Function;
import io.reactivex.subscribers.DisposableSubscriber;
import lombok.extern.slf4j.Slf4j;

import java.time.Duration;
import java.util.NoSuchElementException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeoutException;

@Slf4j
public class TestCircuit {
    CircuitBreaker circuitBreaker;
    CircuitBreakerOperator<Object> circuitBreakerOperator;

    public TestCircuit() {
        this.circuitBreaker = createCircuitBreaker("circuitBreaker");
        this.circuitBreakerOperator = CircuitBreakerOperator.of(circuitBreaker);
    }

    public static void main(String[] args) {
        log.info("Start .....");
        TestCircuit testCircuit = new TestCircuit();
        testCircuit.testCircuit();
        log.info("End .....");
    }

    private void testCircuit() {

        Object[] arr = new Object[]{"a", new TimeoutException(), "b", "c", new TimeoutException(), "d", "e"};

        for (Object o : arr) {
            Object o1 = executeWithFallback(mainMethod(o), (e) -> {
                if (e instanceof CircuitBreakerOpenException || e instanceof TimeoutException || e instanceof CouchbaseException || e instanceof CallNotPermittedException) {
                    return fallbackMethod(o);
                } else {
                    return Flowable.error(e);
                }
            })
                    .blockingLast();
            log.info("Input: {}, Output: {}", o, o1);
        }
    }

    private Flowable<Object> executeWithFallback(Flowable<Object> publisher, Function<Throwable, Flowable<Object>> fallback) {
        return publisher
                .compose(circuitBreakerOperator)
                .onErrorResumeNext(fallback);

    }

    private Flowable<Object> mainMethod(Object o) {
        log.info("Inside method1");
        if (o instanceof TimeoutException) {
            return Flowable.error(new TimeoutException("test"));
        }
        return Flowable.just(new String("method1 -> " + o));

    }

    private Flowable<Object> fallbackMethod(Object o) {
        log.info("Inside method2");
        return Flowable.just(new String("method2 -> pass"));
    }

    <T> CircuitBreaker createCircuitBreaker(String name) {
        return CircuitBreaker.of(name, CircuitBreakerConfig.custom()
                .permittedNumberOfCallsInHalfOpenState(1)
                .enableAutomaticTransitionFromOpenToHalfOpen()
                .ignoreExceptions(NoSuchElementException.class)
                .recordExceptions(TimeoutException.class, CouchbaseException.class, CircuitBreakerOpenException.class)
                .waitDurationInOpenState(Duration.ofSeconds(60))
                .build());
    }
}
```

Logs:
```
16:37:27.774 [main] INFO  TestCircuit - Start .....
16:37:28.315 [main] INFO  TestCircuit - Inside method1
16:37:28.638 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - No Consumers: Event SUCCESS not published
16:37:28.644 [main] INFO  TestCircuit - Input: a, Output: method1 -> a
16:37:28.644 [main] INFO  TestCircuit - Inside method1
16:37:28.668 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - CircuitBreaker 'circuitBreaker' recorded an exception as failure:
java.util.concurrent.TimeoutException: test
	at TestCircuit.mainMethod(TestCircuit.java:61)
	at TestCircuit.testCircuit(TestCircuit.java:39)
	at TestCircuit.main(TestCircuit.java:30)
16:37:28.670 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - No Consumers: Event ERROR not published
16:37:28.670 [main] INFO  TestCircuit - Inside method2
16:37:28.670 [main] INFO  TestCircuit - Input: java.util.concurrent.TimeoutException, Output: method2 -> pass
16:37:28.671 [main] INFO  TestCircuit - Inside method1
16:37:28.672 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - No Consumers: Event SUCCESS not published
16:37:28.673 [main] INFO  TestCircuit - Input: b, Output: method1 -> b
16:37:28.673 [main] INFO  TestCircuit - Inside method1
16:37:28.673 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - No Consumers: Event SUCCESS not published
16:37:28.673 [main] INFO  TestCircuit - Input: c, Output: method1 -> c
16:37:28.673 [main] INFO  TestCircuit - Inside method1
16:37:28.673 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - CircuitBreaker 'circuitBreaker' recorded an exception as failure:
java.util.concurrent.TimeoutException: test
	at TestCircuit.mainMethod(TestCircuit.java:61)
	at TestCircuit.testCircuit(TestCircuit.java:39)
	at TestCircuit.main(TestCircuit.java:30)
16:37:28.674 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - No Consumers: Event ERROR not published
16:37:28.674 [main] INFO  TestCircuit - Inside method2
16:37:28.674 [main] INFO  TestCircuit - Input: java.util.concurrent.TimeoutException, Output: method2 -> pass
16:37:28.674 [main] INFO  TestCircuit - Inside method1
16:37:28.674 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - No Consumers: Event SUCCESS not published
16:37:28.674 [main] INFO  TestCircuit - Input: d, Output: method1 -> d
16:37:28.674 [main] INFO  TestCircuit - Inside method1
16:37:28.675 [main] DEBUG i.g.r.c.i.CircuitBreakerStateMachine - No Consumers: Event SUCCESS not published
16:37:28.675 [main] INFO  TestCircuit - Input: e, Output: method1 -> e
16:37:28.676 [main] INFO  TestCircuit - End .....
```

**Comment by himanshumps** [comment]
The requirement that I am trying to solve is: By default execute methodA .. If there are any recorded exception from method A, open the circuit which waits for a predefined time and route all requests to methodB for that time. Both methodA and methodB return Flowable<Object>

**Comment by RobWin** [comment]
By default the CircuitBreaker requires 10 calls to be recorded, before the failre rate is calculcated. Did you read the [documentation](https://resilience4j.readme.io/docs/circuitbreaker#section-failure-rate-and-slow-call-rate-thresholds)?

Try to set it to a lower value : ` .minimumNumberOfCalls(3)`.
After 2 failures out of 3 calls the circuitbreaker opens.

```
CircuitBreaker.of(name, CircuitBreakerConfig.custom()
                .permittedNumberOfCallsInHalfOpenState(1)
                .minimumNumberOfCalls(3)
                .enableAutomaticTransitionFromOpenToHalfOpen()
                .ignoreExceptions(NoSuchElementException.class)
                .recordExceptions(TimeoutException.class, CouchbaseException.class)
                .waitDurationInOpenState(Duration.ofSeconds(60))
                .build());
```

Instead of `CircuitBreakerOpenException ` please use `CallNotPermittedException`.

**Comment by himanshumps** [comment]
Worked like a charm. Thanks
