### ISSUE TITLE
Spring Boot plugin throws occasionally IllegalStateException: Required to bind 2 arguments, but only bound 1

### ISSUE THREAD

**Issue by yonatang** [resilience4j/resilience4j#919]
Resilience4j version: `1.3.1`

Java version:
```
openjdk version "11.0.1" 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+2 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+2 (build 11.0.1+13-LTS, mixed mode)
```
---
When going through a high rate of failures with `@CircuitBreaker`, `@Retry` and `@TimeLimiter` enabled for a method that returns `CompletableFuture` with a low `waitDurationInOpenState` setting, it will occasionally throw this exception:
```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Required to bind 2 arguments, but only bound 1 (JoinPointMatch was NOT bound in invocation)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.lambda$handleJoinPointCompletableFuture$0(CircuitBreakerAspect.java:178)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.lambda$decorateCompletionStage$1(CircuitBreaker.java:110)
	at io.github.resilience4j.circuitbreaker.CircuitBreaker.executeCompletionStage(CircuitBreaker.java:781)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.handleJoinPointCompletableFuture(CircuitBreakerAspect.java:174)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.proceed(CircuitBreakerAspect.java:133)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.circuitBreakerAroundAdvice(CircuitBreakerAspect.java:112)
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at io.github.resilience4j.retry.configure.RetryAspect.lambda$handleJoinPointCompletableFuture$0(RetryAspect.java:194)
	at io.github.resilience4j.retry.Retry$AsyncRetryBlock.run(Retry.java:652)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Required to bind 2 arguments, but only bound 1 (JoinPointMatch was NOT bound in invocation)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.argBinding(AbstractAspectJAdvice.java:605)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at io.github.resilience4j.circuitbreaker.configure.CircuitBreakerAspect.lambda$handleJoinPointCompletableFuture$0(CircuitBreakerAspect.java:176)
	... 22 more
``` 

This requires a bit more than JUnit to reproduce. Luckily, I was able to simplify and put the entire flow in a single Spring Boot app. The test file + pom.xml are available in this gist: https://gist.github.com/yonatang/d0bffd73ce9cca241c4b59779d697f83

When I run it locally, it will fail with the exception above about 50 times out of 1000. I believe this can vary on the HW type, please let me know if you have a problem reproducing it.

**Comment by Romeh** [comment]
@yonatang  small question , why @EnableAsync(proxyTargetClass = true) is used in ur example ?

**Comment by RobWin** [comment]
Because the `BadService` does not have an interface.
Unfortunately it's using CglibAopProxy then.

**Comment by Mo-Ting** [comment]
Hi, I also encounter this exception when use the Retry module. Even I make sure that my service implements its interface. Do you have further answer on this issue? Thanks.

**Comment by bryanlee-pugh** [comment]
I am also running into this.
