### ISSUE TITLE
CIrcuit breaker is not getting applied on  Google cloud run

### ISSUE THREAD

**Issue by manzarul** [resilience4j/resilience4j#951]
Resilience4j version: 1.2.0

Java version:11
Circuit breake is getting applied during local machine test , but when same code got deployed on GCP it's not working.
Code:

```
 @Override
    @CircuitBreaker(name = "circuitInstance", fallbackMethod = "distanceFallback")
    public Mono<DistanceResponse> postRequest(String url, String requestBody, Map<String, String> headers,
                    DistanceResponse response) {
        log.info("Calculat distance call started");
        WebClient client = cretaeWebCient(url, headers);
        try {
            System.out.println("Latest code updated");
            DistanceResponse distanceResp = client.post()
                            .body(BodyInserters.fromPublisher(Mono.just(requestBody), String.class)).retrieve()
                            .bodyToMono(DistanceResponse.class).block(Duration.ofMillis(MAX_WAITING_RESPONSE_TIME));
            return Mono.just(enhanceDistanceResponse(distanceResp, requestBody));
        } catch (Exception e) {
            System.out.println("Error occured " + e);
            throw new ExternalCallException(HttpStatus.BAD_GATEWAY, "Time out exception");
        }
    }
```

----------------------
```
public Mono<DistanceResponse> distanceFallback(String url, String requestBody, Map<String, String> headers,
                    DistanceResponse response, ExternalCallException exception) {
        DistanceResponse distanceCachedResp = new DistanceResponse();
        try {
            log.info("Data is served from distanceFallback call");
            DistanceRequest distanceReq = mapper.readValue(requestBody, DistanceRequest.class);
            distanceCachedResp.setResponse(getDefaultDistanceResponseList(distanceReq));
        } catch (Exception e) {
            log.error("Exception occured during circuit breaker fall back call." + e);
        }
        return Mono.just(distanceCachedResp);
    }
```

---------Pom
```
<dependencies>
		<!-- Spring Web flux dependencies - for reactive programming -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>

		<!-- Firestore - No SQL database dependencies -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-data-firestore</artifactId>
		</dependency>

		<!-- Redis - caching dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis-reactive</artifactId>
		</dependency>

		<!-- Stackdriver Logging -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-logging</artifactId>
		</dependency>

		<!-- Stackdriver Trace -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-trace</artifactId>
		</dependency>

		<!-- Spring boot actuators -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<!-- Lombok -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>compile</scope>
		</dependency>

		<!-- Spring boot tests -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.projectreactor</groupId>
			<artifactId>reactor-test</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- For reactor debugging, could be removed in prod to reduce memory -->
		<dependency>
			<groupId>io.projectreactor.tools</groupId>
			<artifactId>blockhound</artifactId>
			<version>1.0.2.RELEASE</version>
		</dependency>
                <!--resilience4j jar for circuit breaker-->
               <dependency>
                        <groupId>io.github.resilience4j</groupId>
                        <artifactId>resilience4j-spring-boot2</artifactId>
                        <version>1.2.0</version>
              </dependency>
              <dependency>
                       <groupId>io.github.resilience4j</groupId>
                       <artifactId>resilience4j-reactor</artifactId>
                       <version>1.2.0</version>
              </dependency> 
	</dependencies>
```

-------Some error on Cloud run:
```
2020-04-02 21:59:03.110 CEST[id: 0x25684609, L:/169.254.8.1:26065 - R:distance-service-test1-33fqjj3c4q-ez.a.run.app/216.239.36.53:443] The connection observed an error javax.net.ssl.SSLException: handshake timed out at io.netty.handler.ssl.SslHandler$5.run(SslHandler.java:2001) at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.base/java.lang.Thread.run(Unknown Source) 
```

Thanks for raising a Resilience4j issue.
Please replace this text with a brief description of your problem along with the versions you are using.
If possible, please also consider putting together a complete JUnit test that reproduces the issue.

**Comment by Romeh** [comment]
@manzarul 
the reported error has nothing to do with resilience4j , it is SSL handshake timeout error so you need to review your HTTS certificate setup between your services in your deployment cluster .

Locally u do not have that error as i guess u work over HTTP without any SSL local setup so that is why you do not see that error .

**Comment by RobWin** [comment]
Hi @manzarul,
your reactive code is wrong. You are still trying to implement it in an imperative style. You should not throw exceptions like this:

```
throw new ExternalCallException(HttpStatus.BAD_GATEWAY, "Time out exception");
```

Instead you should use
```return Mono.error()````

**Comment by manzarul** [comment]
Thanks @RobWin  When i used  return Mono.error()  instead of thorwing exception , Circuit breaker is not getting invoked. 
Do we need to configure any thing else as well.

**Comment by RobWin** [comment]
It's difficult to say. 
You didn't paste your config.  I assume there is still something wrong in your reactive code.

**Comment by manzarul** [comment]
application.yml
--------
resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 20
            minimumNumberOfCalls: 10
            permittedNumberOfCallsInHalfOpenState: 5
            waitDurationInOpenState: 3000
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
    instances:
        circuitInstance:
            baseConfig: default
            waitDurationInOpenState: 5000

with application.yml every thing is in place.

**Comment by RobWin** [comment]
Could you please show me your updated reactive code?
